/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_HW_TREZOR_MESSAGES_DEBUG_MESSAGES_DEBUG_PB_H_INCLUDED
#define PB_HW_TREZOR_MESSAGES_DEBUG_MESSAGES_DEBUG_PB_H_INCLUDED
#include "pb.h"
#include "messages.pb.h"
#include "messages-common.pb.h"
#include "messages-management.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _DebugSwipeDirection {
    DebugSwipeDirection_UP = 0,
    DebugSwipeDirection_DOWN = 1,
    DebugSwipeDirection_LEFT = 2,
    DebugSwipeDirection_RIGHT = 3
} DebugSwipeDirection;

typedef enum _DebugButton {
    DebugButton_NO = 0,
    DebugButton_YES = 1,
    DebugButton_INFO = 2
} DebugButton;

/* Struct definitions */
typedef struct _DebugLinkDecision {
    bool has_button;
    DebugButton button;
    bool has_swipe;
    DebugSwipeDirection swipe;
    bool has_input;
    char input[33];
    bool has_wait;
    bool wait;
    bool has_hold_ms;
    uint32_t hold_ms;
} DebugLinkDecision;

typedef struct _DebugLinkReseedRandom {
    bool has_value;
    uint32_t value;
} DebugLinkReseedRandom;

typedef struct _DebugLinkGetState {
    bool has_wait_word_list;
    bool wait_word_list;
    bool has_wait_word_pos;
    bool wait_word_pos;
    bool has_wait_layout;
    bool wait_layout;
} DebugLinkGetState;

typedef PB_BYTES_ARRAY_T(1024) DebugLinkState_layout_t;
typedef PB_BYTES_ARRAY_T(240) DebugLinkState_mnemonic_secret_t;
typedef PB_BYTES_ARRAY_T(128) DebugLinkState_reset_entropy_t;
typedef struct _DebugLinkState {
    bool has_layout;
    DebugLinkState_layout_t layout;
    bool has_pin;
    char pin[51];
    bool has_matrix;
    char matrix[10];
    bool has_mnemonic_secret;
    DebugLinkState_mnemonic_secret_t mnemonic_secret;
    bool has_node;
    HDNodeType node;
    bool has_passphrase_protection;
    bool passphrase_protection;
    bool has_reset_word;
    char reset_word[12];
    bool has_reset_entropy;
    DebugLinkState_reset_entropy_t reset_entropy;
    bool has_recovery_fake_word;
    char recovery_fake_word[12];
    bool has_recovery_word_pos;
    uint32_t recovery_word_pos;
    bool has_reset_word_pos;
    uint32_t reset_word_pos;
    bool has_mnemonic_type;
    BackupType mnemonic_type;
} DebugLinkState;

typedef struct _DebugLinkStop {
    char dummy_field;
} DebugLinkStop;

typedef struct _DebugLinkLog {
    bool has_level;
    uint32_t level;
    bool has_bucket;
    char bucket[33];
    bool has_text;
    char text[256];
} DebugLinkLog;

typedef struct _DebugLinkMemoryRead {
    bool has_address;
    uint32_t address;
    bool has_length;
    uint32_t length;
} DebugLinkMemoryRead;

typedef PB_BYTES_ARRAY_T(1024) DebugLinkMemory_memory_t;
typedef struct _DebugLinkMemory {
    bool has_memory;
    DebugLinkMemory_memory_t memory;
} DebugLinkMemory;

typedef PB_BYTES_ARRAY_T(1024) DebugLinkMemoryWrite_memory_t;
typedef struct _DebugLinkMemoryWrite {
    bool has_address;
    uint32_t address;
    bool has_memory;
    DebugLinkMemoryWrite_memory_t memory;
    bool has_flash;
    bool flash;
} DebugLinkMemoryWrite;

typedef struct _DebugLinkFlashErase {
    bool has_sector;
    uint32_t sector;
} DebugLinkFlashErase;

typedef struct _DebugLinkEraseSdCard {
    bool has_format;
    bool format;
} DebugLinkEraseSdCard;

typedef struct _DebugLinkWatchLayout {
    bool has_watch;
    bool watch;
} DebugLinkWatchLayout;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _DebugSwipeDirection_MIN DebugSwipeDirection_UP
#define _DebugSwipeDirection_MAX DebugSwipeDirection_RIGHT
#define _DebugSwipeDirection_ARRAYSIZE ((DebugSwipeDirection)(DebugSwipeDirection_RIGHT+1))

#define _DebugButton_MIN DebugButton_NO
#define _DebugButton_MAX DebugButton_INFO
#define _DebugButton_ARRAYSIZE ((DebugButton)(DebugButton_INFO+1))

#define DebugLinkDecision_button_ENUMTYPE DebugButton
#define DebugLinkDecision_swipe_ENUMTYPE DebugSwipeDirection



#define DebugLinkState_mnemonic_type_ENUMTYPE BackupType










/* Initializer values for message structs */
#define DebugLinkDecision_init_default           {false, _DebugButton_MIN, false, _DebugSwipeDirection_MIN, false, "", false, 0, false, 0}
#define DebugLinkReseedRandom_init_default       {false, 0}
#define DebugLinkGetState_init_default           {false, 0, false, 0, false, 0}
#define DebugLinkState_init_default              {false, {0, {0}}, false, "", false, "", false, {0, {0}}, false, HDNodeType_init_default, false, 0, false, "", false, {0, {0}}, false, "", false, 0, false, 0, false, _BackupType_MIN}
#define DebugLinkStop_init_default               {0}
#define DebugLinkLog_init_default                {false, 0, false, "", false, ""}
#define DebugLinkMemoryRead_init_default         {false, 0, false, 0}
#define DebugLinkMemory_init_default             {false, {0, {0}}}
#define DebugLinkMemoryWrite_init_default        {false, 0, false, {0, {0}}, false, 0}
#define DebugLinkFlashErase_init_default         {false, 0}
#define DebugLinkEraseSdCard_init_default        {false, 0}
#define DebugLinkWatchLayout_init_default        {false, 0}
#define DebugLinkDecision_init_zero              {false, _DebugButton_MIN, false, _DebugSwipeDirection_MIN, false, "", false, 0, false, 0}
#define DebugLinkReseedRandom_init_zero          {false, 0}
#define DebugLinkGetState_init_zero              {false, 0, false, 0, false, 0}
#define DebugLinkState_init_zero                 {false, {0, {0}}, false, "", false, "", false, {0, {0}}, false, HDNodeType_init_zero, false, 0, false, "", false, {0, {0}}, false, "", false, 0, false, 0, false, _BackupType_MIN}
#define DebugLinkStop_init_zero                  {0}
#define DebugLinkLog_init_zero                   {false, 0, false, "", false, ""}
#define DebugLinkMemoryRead_init_zero            {false, 0, false, 0}
#define DebugLinkMemory_init_zero                {false, {0, {0}}}
#define DebugLinkMemoryWrite_init_zero           {false, 0, false, {0, {0}}, false, 0}
#define DebugLinkFlashErase_init_zero            {false, 0}
#define DebugLinkEraseSdCard_init_zero           {false, 0}
#define DebugLinkWatchLayout_init_zero           {false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define DebugLinkDecision_button_tag             1
#define DebugLinkDecision_swipe_tag              2
#define DebugLinkDecision_input_tag              3
#define DebugLinkDecision_wait_tag               6
#define DebugLinkDecision_hold_ms_tag            7
#define DebugLinkReseedRandom_value_tag          1
#define DebugLinkGetState_wait_word_list_tag     1
#define DebugLinkGetState_wait_word_pos_tag      2
#define DebugLinkGetState_wait_layout_tag        3
#define DebugLinkState_layout_tag                1
#define DebugLinkState_pin_tag                   2
#define DebugLinkState_matrix_tag                3
#define DebugLinkState_mnemonic_secret_tag       4
#define DebugLinkState_node_tag                  5
#define DebugLinkState_passphrase_protection_tag 6
#define DebugLinkState_reset_word_tag            7
#define DebugLinkState_reset_entropy_tag         8
#define DebugLinkState_recovery_fake_word_tag    9
#define DebugLinkState_recovery_word_pos_tag     10
#define DebugLinkState_reset_word_pos_tag        11
#define DebugLinkState_mnemonic_type_tag         12
#define DebugLinkLog_level_tag                   1
#define DebugLinkLog_bucket_tag                  2
#define DebugLinkLog_text_tag                    3
#define DebugLinkMemoryRead_address_tag          1
#define DebugLinkMemoryRead_length_tag           2
#define DebugLinkMemory_memory_tag               1
#define DebugLinkMemoryWrite_address_tag         1
#define DebugLinkMemoryWrite_memory_tag          2
#define DebugLinkMemoryWrite_flash_tag           3
#define DebugLinkFlashErase_sector_tag           1
#define DebugLinkEraseSdCard_format_tag          1
#define DebugLinkWatchLayout_watch_tag           1

/* Struct field encoding specification for nanopb */
#define DebugLinkDecision_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    button,            1) \
X(a, STATIC,   OPTIONAL, UENUM,    swipe,             2) \
X(a, STATIC,   OPTIONAL, STRING,   input,             3) \
X(a, STATIC,   OPTIONAL, BOOL,     wait,              6) \
X(a, STATIC,   OPTIONAL, UINT32,   hold_ms,           7)
#define DebugLinkDecision_CALLBACK NULL
#define DebugLinkDecision_DEFAULT NULL

#define DebugLinkReseedRandom_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   value,             1)
#define DebugLinkReseedRandom_CALLBACK NULL
#define DebugLinkReseedRandom_DEFAULT NULL

#define DebugLinkGetState_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     wait_word_list,    1) \
X(a, STATIC,   OPTIONAL, BOOL,     wait_word_pos,     2) \
X(a, STATIC,   OPTIONAL, BOOL,     wait_layout,       3)
#define DebugLinkGetState_CALLBACK NULL
#define DebugLinkGetState_DEFAULT NULL

#define DebugLinkState_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BYTES,    layout,            1) \
X(a, STATIC,   OPTIONAL, STRING,   pin,               2) \
X(a, STATIC,   OPTIONAL, STRING,   matrix,            3) \
X(a, STATIC,   OPTIONAL, BYTES,    mnemonic_secret,   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  node,              5) \
X(a, STATIC,   OPTIONAL, BOOL,     passphrase_protection,   6) \
X(a, STATIC,   OPTIONAL, STRING,   reset_word,        7) \
X(a, STATIC,   OPTIONAL, BYTES,    reset_entropy,     8) \
X(a, STATIC,   OPTIONAL, STRING,   recovery_fake_word,   9) \
X(a, STATIC,   OPTIONAL, UINT32,   recovery_word_pos,  10) \
X(a, STATIC,   OPTIONAL, UINT32,   reset_word_pos,   11) \
X(a, STATIC,   OPTIONAL, UENUM,    mnemonic_type,    12)
#define DebugLinkState_CALLBACK NULL
#define DebugLinkState_DEFAULT NULL
#define DebugLinkState_node_MSGTYPE HDNodeType

#define DebugLinkStop_FIELDLIST(X, a) \

#define DebugLinkStop_CALLBACK NULL
#define DebugLinkStop_DEFAULT NULL

#define DebugLinkLog_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   level,             1) \
X(a, STATIC,   OPTIONAL, STRING,   bucket,            2) \
X(a, STATIC,   OPTIONAL, STRING,   text,              3)
#define DebugLinkLog_CALLBACK NULL
#define DebugLinkLog_DEFAULT NULL

#define DebugLinkMemoryRead_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   address,           1) \
X(a, STATIC,   OPTIONAL, UINT32,   length,            2)
#define DebugLinkMemoryRead_CALLBACK NULL
#define DebugLinkMemoryRead_DEFAULT NULL

#define DebugLinkMemory_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BYTES,    memory,            1)
#define DebugLinkMemory_CALLBACK NULL
#define DebugLinkMemory_DEFAULT NULL

#define DebugLinkMemoryWrite_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   address,           1) \
X(a, STATIC,   OPTIONAL, BYTES,    memory,            2) \
X(a, STATIC,   OPTIONAL, BOOL,     flash,             3)
#define DebugLinkMemoryWrite_CALLBACK NULL
#define DebugLinkMemoryWrite_DEFAULT NULL

#define DebugLinkFlashErase_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   sector,            1)
#define DebugLinkFlashErase_CALLBACK NULL
#define DebugLinkFlashErase_DEFAULT NULL

#define DebugLinkEraseSdCard_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     format,            1)
#define DebugLinkEraseSdCard_CALLBACK NULL
#define DebugLinkEraseSdCard_DEFAULT NULL

#define DebugLinkWatchLayout_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     watch,             1)
#define DebugLinkWatchLayout_CALLBACK NULL
#define DebugLinkWatchLayout_DEFAULT NULL

extern const pb_msgdesc_t DebugLinkDecision_msg;
extern const pb_msgdesc_t DebugLinkReseedRandom_msg;
extern const pb_msgdesc_t DebugLinkGetState_msg;
extern const pb_msgdesc_t DebugLinkState_msg;
extern const pb_msgdesc_t DebugLinkStop_msg;
extern const pb_msgdesc_t DebugLinkLog_msg;
extern const pb_msgdesc_t DebugLinkMemoryRead_msg;
extern const pb_msgdesc_t DebugLinkMemory_msg;
extern const pb_msgdesc_t DebugLinkMemoryWrite_msg;
extern const pb_msgdesc_t DebugLinkFlashErase_msg;
extern const pb_msgdesc_t DebugLinkEraseSdCard_msg;
extern const pb_msgdesc_t DebugLinkWatchLayout_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define DebugLinkDecision_fields &DebugLinkDecision_msg
#define DebugLinkReseedRandom_fields &DebugLinkReseedRandom_msg
#define DebugLinkGetState_fields &DebugLinkGetState_msg
#define DebugLinkState_fields &DebugLinkState_msg
#define DebugLinkStop_fields &DebugLinkStop_msg
#define DebugLinkLog_fields &DebugLinkLog_msg
#define DebugLinkMemoryRead_fields &DebugLinkMemoryRead_msg
#define DebugLinkMemory_fields &DebugLinkMemory_msg
#define DebugLinkMemoryWrite_fields &DebugLinkMemoryWrite_msg
#define DebugLinkFlashErase_fields &DebugLinkFlashErase_msg
#define DebugLinkEraseSdCard_fields &DebugLinkEraseSdCard_msg
#define DebugLinkWatchLayout_fields &DebugLinkWatchLayout_msg

/* Maximum encoded size of messages (where known) */
#define DebugLinkDecision_size                   46
#define DebugLinkEraseSdCard_size                2
#define DebugLinkFlashErase_size                 6
#define DebugLinkGetState_size                   6
#define DebugLinkLog_size                        298
#define DebugLinkMemoryRead_size                 12
#define DebugLinkMemoryWrite_size                1035
#define DebugLinkMemory_size                     1027
#define DebugLinkReseedRandom_size               6
#define DebugLinkState_size                      1629
#define DebugLinkStop_size                       0
#define DebugLinkWatchLayout_size                2

/* Mapping from canonical names (mangle_names or overridden package name) */
#define hw_trezor_messages_debug_DebugLinkDecision DebugLinkDecision
#define hw_trezor_messages_debug_DebugLinkDecision_DebugSwipeDirection DebugSwipeDirection
#define hw_trezor_messages_debug_DebugLinkDecision_DebugButton DebugButton
#define hw_trezor_messages_debug_DebugLinkLayout DebugLinkLayout
#define hw_trezor_messages_debug_DebugLinkReseedRandom DebugLinkReseedRandom
#define hw_trezor_messages_debug_DebugLinkRecordScreen DebugLinkRecordScreen
#define hw_trezor_messages_debug_DebugLinkGetState DebugLinkGetState
#define hw_trezor_messages_debug_DebugLinkState DebugLinkState
#define hw_trezor_messages_debug_DebugLinkStop DebugLinkStop
#define hw_trezor_messages_debug_DebugLinkLog DebugLinkLog
#define hw_trezor_messages_debug_DebugLinkMemoryRead DebugLinkMemoryRead
#define hw_trezor_messages_debug_DebugLinkMemory DebugLinkMemory
#define hw_trezor_messages_debug_DebugLinkMemoryWrite DebugLinkMemoryWrite
#define hw_trezor_messages_debug_DebugLinkFlashErase DebugLinkFlashErase
#define hw_trezor_messages_debug_DebugLinkEraseSdCard DebugLinkEraseSdCard
#define hw_trezor_messages_debug_DebugLinkWatchLayout DebugLinkWatchLayout

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
