/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "messages-management.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Initialize, Initialize, AUTO)


PB_BIND(GetFeatures, GetFeatures, AUTO)


PB_BIND(Features, Features, 2)


PB_BIND(LockDevice, LockDevice, AUTO)


PB_BIND(EndSession, EndSession, AUTO)


PB_BIND(ApplySettings, ApplySettings, 2)


PB_BIND(ApplyFlags, ApplyFlags, AUTO)


PB_BIND(ChangePin, ChangePin, AUTO)


PB_BIND(ChangeWipeCode, ChangeWipeCode, AUTO)


PB_BIND(SdProtect, SdProtect, AUTO)


PB_BIND(Ping, Ping, 2)


PB_BIND(Cancel, Cancel, AUTO)


PB_BIND(GetEntropy, GetEntropy, AUTO)


PB_BIND(Entropy, Entropy, 2)


PB_BIND(WipeDevice, WipeDevice, AUTO)


PB_BIND(LoadDevice, LoadDevice, 2)


PB_BIND(ResetDevice, ResetDevice, AUTO)


PB_BIND(BackupDevice, BackupDevice, AUTO)


PB_BIND(EntropyRequest, EntropyRequest, AUTO)


PB_BIND(EntropyAck, EntropyAck, AUTO)


PB_BIND(RecoveryDevice, RecoveryDevice, AUTO)


PB_BIND(WordRequest, WordRequest, AUTO)


PB_BIND(WordAck, WordAck, AUTO)


PB_BIND(SetU2FCounter, SetU2FCounter, AUTO)


PB_BIND(GetNextU2FCounter, GetNextU2FCounter, AUTO)


PB_BIND(NextU2FCounter, NextU2FCounter, AUTO)


PB_BIND(DoPreauthorized, DoPreauthorized, AUTO)


PB_BIND(PreauthorizedRequest, PreauthorizedRequest, AUTO)


PB_BIND(CancelAuthorization, CancelAuthorization, AUTO)


PB_BIND(RebootToBootloader, RebootToBootloader, AUTO)


PB_BIND(DeviceCertificateAck, DeviceCertificateAck, AUTO)


PB_BIND(DeviceCertificate, DeviceCertificate, 2)


PB_BIND(VerifyDeviceAck, VerifyDeviceAck, AUTO)


PB_BIND(VerifyDevice, VerifyDevice, AUTO)


PB_BIND(GetNonce, GetNonce, AUTO)


PB_BIND(Nonce, Nonce, AUTO)


PB_BIND(UnlockPath, UnlockPath, AUTO)


PB_BIND(UnlockedPathRequest, UnlockedPathRequest, AUTO)









