/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "messages-bitcoin.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MultisigRedeemScriptType, MultisigRedeemScriptType, 2)


PB_BIND(HDNodePathType, HDNodePathType, AUTO)


PB_BIND(GetPublicKey, GetPublicKey, AUTO)


PB_BIND(PublicKey, PublicKey, AUTO)


PB_BIND(GetAddress, GetAddress, 4)


PB_BIND(Address, Address, AUTO)


PB_BIND(GetOwnershipId, GetOwnershipId, 4)


PB_BIND(OwnershipId, OwnershipId, AUTO)


PB_BIND(SignMessage, SignMessage, 2)


PB_BIND(MessageSignature, MessageSignature, AUTO)


PB_BIND(VerifyMessage, VerifyMessage, 2)


PB_BIND(SignTx, SignTx, AUTO)


PB_BIND(CoinJoinRequest, CoinJoinRequest, AUTO)


PB_BIND(TxRequest, TxRequest, 2)


PB_BIND(TxRequestDetailsType, TxRequestDetailsType, AUTO)


PB_BIND(TxRequestSerializedType, TxRequestSerializedType, 2)


PB_BIND(TxAck, TxAck, 4)


PB_BIND(TransactionType, TransactionType, 4)


PB_BIND(TxInputType, TxInputType, 4)


PB_BIND(TxOutputBinType, TxOutputBinType, 2)


PB_BIND(TxOutputType, TxOutputType, 4)


PB_BIND(TxInput, TxInput, 4)


PB_BIND(TxOutput, TxOutput, 4)


PB_BIND(PrevTx, PrevTx, AUTO)


PB_BIND(PrevInput, PrevInput, 2)


PB_BIND(PrevOutput, PrevOutput, 2)


PB_BIND(TxAckInput, TxAckInput, 4)


PB_BIND(TxAckInputWrapper, TxAckInputWrapper, 4)


PB_BIND(TxAckOutput, TxAckOutput, 4)


PB_BIND(TxAckOutputWrapper, TxAckOutputWrapper, 4)


PB_BIND(TxAckPrevMeta, TxAckPrevMeta, AUTO)


PB_BIND(TxAckPrevInput, TxAckPrevInput, 2)


PB_BIND(TxAckPrevInputWrapper, TxAckPrevInputWrapper, 2)


PB_BIND(TxAckPrevOutput, TxAckPrevOutput, 2)


PB_BIND(TxAckPrevOutputWrapper, TxAckPrevOutputWrapper, 2)


PB_BIND(TxAckPrevExtraData, TxAckPrevExtraData, AUTO)


PB_BIND(TxAckPrevExtraDataWrapper, TxAckPrevExtraDataWrapper, AUTO)


PB_BIND(GetOwnershipProof, GetOwnershipProof, 4)


PB_BIND(OwnershipProof, OwnershipProof, AUTO)


PB_BIND(AuthorizeCoinJoin, AuthorizeCoinJoin, AUTO)








