/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "messages-crypto.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CipherKeyValue, CipherKeyValue, 2)


PB_BIND(CipheredKeyValue, CipheredKeyValue, 2)


PB_BIND(IdentityType, IdentityType, 2)


PB_BIND(SignIdentity, SignIdentity, 2)


PB_BIND(SignedIdentity, SignedIdentity, AUTO)


PB_BIND(GetECDHSessionKey, GetECDHSessionKey, 2)


PB_BIND(ECDHSessionKey, ECDHSessionKey, AUTO)



