// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages-ethereum-definitions.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_messages_2dethereum_2ddefinitions_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_messages_2dethereum_2ddefinitions_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_messages_2dethereum_2ddefinitions_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_messages_2dethereum_2ddefinitions_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_messages_2dethereum_2ddefinitions_2eproto;
namespace hw {
namespace trezor {
namespace messages {
namespace ethereum_definitions {
class EthereumDefinitions;
class EthereumDefinitionsDefaultTypeInternal;
extern EthereumDefinitionsDefaultTypeInternal _EthereumDefinitions_default_instance_;
class EthereumNetworkInfo;
class EthereumNetworkInfoDefaultTypeInternal;
extern EthereumNetworkInfoDefaultTypeInternal _EthereumNetworkInfo_default_instance_;
class EthereumTokenInfo;
class EthereumTokenInfoDefaultTypeInternal;
extern EthereumTokenInfoDefaultTypeInternal _EthereumTokenInfo_default_instance_;
}  // namespace ethereum_definitions
}  // namespace messages
}  // namespace trezor
}  // namespace hw
PROTOBUF_NAMESPACE_OPEN
template<> ::hw::trezor::messages::ethereum_definitions::EthereumDefinitions* Arena::CreateMaybeMessage<::hw::trezor::messages::ethereum_definitions::EthereumDefinitions>(Arena*);
template<> ::hw::trezor::messages::ethereum_definitions::EthereumNetworkInfo* Arena::CreateMaybeMessage<::hw::trezor::messages::ethereum_definitions::EthereumNetworkInfo>(Arena*);
template<> ::hw::trezor::messages::ethereum_definitions::EthereumTokenInfo* Arena::CreateMaybeMessage<::hw::trezor::messages::ethereum_definitions::EthereumTokenInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace hw {
namespace trezor {
namespace messages {
namespace ethereum_definitions {

enum EthereumDefinitionType : int {
  NETWORK = 0,
  TOKEN = 1
};
bool EthereumDefinitionType_IsValid(int value);
constexpr EthereumDefinitionType EthereumDefinitionType_MIN = NETWORK;
constexpr EthereumDefinitionType EthereumDefinitionType_MAX = TOKEN;
constexpr int EthereumDefinitionType_ARRAYSIZE = EthereumDefinitionType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EthereumDefinitionType_descriptor();
template<typename T>
inline const std::string& EthereumDefinitionType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EthereumDefinitionType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EthereumDefinitionType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EthereumDefinitionType_descriptor(), enum_t_value);
}
inline bool EthereumDefinitionType_Parse(
    const std::string& name, EthereumDefinitionType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EthereumDefinitionType>(
    EthereumDefinitionType_descriptor(), name, value);
}
// ===================================================================

class EthereumNetworkInfo :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo) */ {
 public:
  EthereumNetworkInfo();
  virtual ~EthereumNetworkInfo();

  EthereumNetworkInfo(const EthereumNetworkInfo& from);
  EthereumNetworkInfo(EthereumNetworkInfo&& from) noexcept
    : EthereumNetworkInfo() {
    *this = ::std::move(from);
  }

  inline EthereumNetworkInfo& operator=(const EthereumNetworkInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline EthereumNetworkInfo& operator=(EthereumNetworkInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EthereumNetworkInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EthereumNetworkInfo* internal_default_instance() {
    return reinterpret_cast<const EthereumNetworkInfo*>(
               &_EthereumNetworkInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(EthereumNetworkInfo& a, EthereumNetworkInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(EthereumNetworkInfo* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EthereumNetworkInfo* New() const final {
    return CreateMaybeMessage<EthereumNetworkInfo>(nullptr);
  }

  EthereumNetworkInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EthereumNetworkInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EthereumNetworkInfo& from);
  void MergeFrom(const EthereumNetworkInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EthereumNetworkInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_messages_2dethereum_2ddefinitions_2eproto);
    return ::descriptor_table_messages_2dethereum_2ddefinitions_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSymbolFieldNumber = 2,
    kNameFieldNumber = 4,
    kIconFieldNumber = 101,
    kChainIdFieldNumber = 1,
    kSlip44FieldNumber = 3,
    kPrimaryColorFieldNumber = 102,
  };
  // required string symbol = 2;
  bool has_symbol() const;
  void clear_symbol();
  const std::string& symbol() const;
  void set_symbol(const std::string& value);
  void set_symbol(std::string&& value);
  void set_symbol(const char* value);
  void set_symbol(const char* value, size_t size);
  std::string* mutable_symbol();
  std::string* release_symbol();
  void set_allocated_symbol(std::string* symbol);

  // required string name = 4;
  bool has_name() const;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);

  // optional string icon = 101;
  bool has_icon() const;
  void clear_icon();
  const std::string& icon() const;
  void set_icon(const std::string& value);
  void set_icon(std::string&& value);
  void set_icon(const char* value);
  void set_icon(const char* value, size_t size);
  std::string* mutable_icon();
  std::string* release_icon();
  void set_allocated_icon(std::string* icon);

  // required uint64 chain_id = 1;
  bool has_chain_id() const;
  void clear_chain_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 chain_id() const;
  void set_chain_id(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // required uint32 slip44 = 3;
  bool has_slip44() const;
  void clear_slip44();
  ::PROTOBUF_NAMESPACE_ID::uint32 slip44() const;
  void set_slip44(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // optional uint64 primary_color = 102;
  bool has_primary_color() const;
  void clear_primary_color();
  ::PROTOBUF_NAMESPACE_ID::uint64 primary_color() const;
  void set_primary_color(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // @@protoc_insertion_point(class_scope:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr symbol_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr icon_;
  ::PROTOBUF_NAMESPACE_ID::uint64 chain_id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 slip44_;
  ::PROTOBUF_NAMESPACE_ID::uint64 primary_color_;
  friend struct ::TableStruct_messages_2dethereum_2ddefinitions_2eproto;
};
// -------------------------------------------------------------------

class EthereumTokenInfo :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo) */ {
 public:
  EthereumTokenInfo();
  virtual ~EthereumTokenInfo();

  EthereumTokenInfo(const EthereumTokenInfo& from);
  EthereumTokenInfo(EthereumTokenInfo&& from) noexcept
    : EthereumTokenInfo() {
    *this = ::std::move(from);
  }

  inline EthereumTokenInfo& operator=(const EthereumTokenInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline EthereumTokenInfo& operator=(EthereumTokenInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EthereumTokenInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EthereumTokenInfo* internal_default_instance() {
    return reinterpret_cast<const EthereumTokenInfo*>(
               &_EthereumTokenInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(EthereumTokenInfo& a, EthereumTokenInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(EthereumTokenInfo* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EthereumTokenInfo* New() const final {
    return CreateMaybeMessage<EthereumTokenInfo>(nullptr);
  }

  EthereumTokenInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EthereumTokenInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EthereumTokenInfo& from);
  void MergeFrom(const EthereumTokenInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EthereumTokenInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hw.trezor.messages.ethereum_definitions.EthereumTokenInfo";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_messages_2dethereum_2ddefinitions_2eproto);
    return ::descriptor_table_messages_2dethereum_2ddefinitions_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAddressFieldNumber = 1,
    kSymbolFieldNumber = 3,
    kNameFieldNumber = 5,
    kChainIdFieldNumber = 2,
    kDecimalsFieldNumber = 4,
  };
  // required bytes address = 1;
  bool has_address() const;
  void clear_address();
  const std::string& address() const;
  void set_address(const std::string& value);
  void set_address(std::string&& value);
  void set_address(const char* value);
  void set_address(const void* value, size_t size);
  std::string* mutable_address();
  std::string* release_address();
  void set_allocated_address(std::string* address);

  // required string symbol = 3;
  bool has_symbol() const;
  void clear_symbol();
  const std::string& symbol() const;
  void set_symbol(const std::string& value);
  void set_symbol(std::string&& value);
  void set_symbol(const char* value);
  void set_symbol(const char* value, size_t size);
  std::string* mutable_symbol();
  std::string* release_symbol();
  void set_allocated_symbol(std::string* symbol);

  // required string name = 5;
  bool has_name() const;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);

  // required uint64 chain_id = 2;
  bool has_chain_id() const;
  void clear_chain_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 chain_id() const;
  void set_chain_id(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // required uint32 decimals = 4;
  bool has_decimals() const;
  void clear_decimals();
  ::PROTOBUF_NAMESPACE_ID::uint32 decimals() const;
  void set_decimals(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // @@protoc_insertion_point(class_scope:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr address_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr symbol_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::uint64 chain_id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 decimals_;
  friend struct ::TableStruct_messages_2dethereum_2ddefinitions_2eproto;
};
// -------------------------------------------------------------------

class EthereumDefinitions :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hw.trezor.messages.ethereum_definitions.EthereumDefinitions) */ {
 public:
  EthereumDefinitions();
  virtual ~EthereumDefinitions();

  EthereumDefinitions(const EthereumDefinitions& from);
  EthereumDefinitions(EthereumDefinitions&& from) noexcept
    : EthereumDefinitions() {
    *this = ::std::move(from);
  }

  inline EthereumDefinitions& operator=(const EthereumDefinitions& from) {
    CopyFrom(from);
    return *this;
  }
  inline EthereumDefinitions& operator=(EthereumDefinitions&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EthereumDefinitions& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EthereumDefinitions* internal_default_instance() {
    return reinterpret_cast<const EthereumDefinitions*>(
               &_EthereumDefinitions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(EthereumDefinitions& a, EthereumDefinitions& b) {
    a.Swap(&b);
  }
  inline void Swap(EthereumDefinitions* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EthereumDefinitions* New() const final {
    return CreateMaybeMessage<EthereumDefinitions>(nullptr);
  }

  EthereumDefinitions* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EthereumDefinitions>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EthereumDefinitions& from);
  void MergeFrom(const EthereumDefinitions& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EthereumDefinitions* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hw.trezor.messages.ethereum_definitions.EthereumDefinitions";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_messages_2dethereum_2ddefinitions_2eproto);
    return ::descriptor_table_messages_2dethereum_2ddefinitions_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEncodedNetworkFieldNumber = 1,
    kEncodedTokenFieldNumber = 2,
  };
  // optional bytes encoded_network = 1;
  bool has_encoded_network() const;
  void clear_encoded_network();
  const std::string& encoded_network() const;
  void set_encoded_network(const std::string& value);
  void set_encoded_network(std::string&& value);
  void set_encoded_network(const char* value);
  void set_encoded_network(const void* value, size_t size);
  std::string* mutable_encoded_network();
  std::string* release_encoded_network();
  void set_allocated_encoded_network(std::string* encoded_network);

  // optional bytes encoded_token = 2;
  bool has_encoded_token() const;
  void clear_encoded_token();
  const std::string& encoded_token() const;
  void set_encoded_token(const std::string& value);
  void set_encoded_token(std::string&& value);
  void set_encoded_token(const char* value);
  void set_encoded_token(const void* value, size_t size);
  std::string* mutable_encoded_token();
  std::string* release_encoded_token();
  void set_allocated_encoded_token(std::string* encoded_token);

  // @@protoc_insertion_point(class_scope:hw.trezor.messages.ethereum_definitions.EthereumDefinitions)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr encoded_network_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr encoded_token_;
  friend struct ::TableStruct_messages_2dethereum_2ddefinitions_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// EthereumNetworkInfo

// required uint64 chain_id = 1;
inline bool EthereumNetworkInfo::has_chain_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void EthereumNetworkInfo::clear_chain_id() {
  chain_id_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 EthereumNetworkInfo::chain_id() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.chain_id)
  return chain_id_;
}
inline void EthereumNetworkInfo::set_chain_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000008u;
  chain_id_ = value;
  // @@protoc_insertion_point(field_set:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.chain_id)
}

// required string symbol = 2;
inline bool EthereumNetworkInfo::has_symbol() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void EthereumNetworkInfo::clear_symbol() {
  symbol_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& EthereumNetworkInfo::symbol() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.symbol)
  return symbol_.GetNoArena();
}
inline void EthereumNetworkInfo::set_symbol(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  symbol_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.symbol)
}
inline void EthereumNetworkInfo::set_symbol(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  symbol_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.symbol)
}
inline void EthereumNetworkInfo::set_symbol(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  symbol_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.symbol)
}
inline void EthereumNetworkInfo::set_symbol(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  symbol_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.symbol)
}
inline std::string* EthereumNetworkInfo::mutable_symbol() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.symbol)
  return symbol_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* EthereumNetworkInfo::release_symbol() {
  // @@protoc_insertion_point(field_release:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.symbol)
  if (!has_symbol()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return symbol_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void EthereumNetworkInfo::set_allocated_symbol(std::string* symbol) {
  if (symbol != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  symbol_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), symbol);
  // @@protoc_insertion_point(field_set_allocated:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.symbol)
}

// required uint32 slip44 = 3;
inline bool EthereumNetworkInfo::has_slip44() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void EthereumNetworkInfo::clear_slip44() {
  slip44_ = 0u;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 EthereumNetworkInfo::slip44() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.slip44)
  return slip44_;
}
inline void EthereumNetworkInfo::set_slip44(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000010u;
  slip44_ = value;
  // @@protoc_insertion_point(field_set:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.slip44)
}

// required string name = 4;
inline bool EthereumNetworkInfo::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void EthereumNetworkInfo::clear_name() {
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& EthereumNetworkInfo::name() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.name)
  return name_.GetNoArena();
}
inline void EthereumNetworkInfo::set_name(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.name)
}
inline void EthereumNetworkInfo::set_name(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.name)
}
inline void EthereumNetworkInfo::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.name)
}
inline void EthereumNetworkInfo::set_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.name)
}
inline std::string* EthereumNetworkInfo::mutable_name() {
  _has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_mutable:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.name)
  return name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* EthereumNetworkInfo::release_name() {
  // @@protoc_insertion_point(field_release:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.name)
  if (!has_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return name_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void EthereumNetworkInfo::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.name)
}

// optional string icon = 101;
inline bool EthereumNetworkInfo::has_icon() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void EthereumNetworkInfo::clear_icon() {
  icon_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& EthereumNetworkInfo::icon() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.icon)
  return icon_.GetNoArena();
}
inline void EthereumNetworkInfo::set_icon(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  icon_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.icon)
}
inline void EthereumNetworkInfo::set_icon(std::string&& value) {
  _has_bits_[0] |= 0x00000004u;
  icon_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.icon)
}
inline void EthereumNetworkInfo::set_icon(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000004u;
  icon_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.icon)
}
inline void EthereumNetworkInfo::set_icon(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000004u;
  icon_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.icon)
}
inline std::string* EthereumNetworkInfo::mutable_icon() {
  _has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_mutable:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.icon)
  return icon_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* EthereumNetworkInfo::release_icon() {
  // @@protoc_insertion_point(field_release:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.icon)
  if (!has_icon()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return icon_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void EthereumNetworkInfo::set_allocated_icon(std::string* icon) {
  if (icon != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  icon_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), icon);
  // @@protoc_insertion_point(field_set_allocated:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.icon)
}

// optional uint64 primary_color = 102;
inline bool EthereumNetworkInfo::has_primary_color() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void EthereumNetworkInfo::clear_primary_color() {
  primary_color_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 EthereumNetworkInfo::primary_color() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.primary_color)
  return primary_color_;
}
inline void EthereumNetworkInfo::set_primary_color(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000020u;
  primary_color_ = value;
  // @@protoc_insertion_point(field_set:hw.trezor.messages.ethereum_definitions.EthereumNetworkInfo.primary_color)
}

// -------------------------------------------------------------------

// EthereumTokenInfo

// required bytes address = 1;
inline bool EthereumTokenInfo::has_address() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void EthereumTokenInfo::clear_address() {
  address_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& EthereumTokenInfo::address() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.address)
  return address_.GetNoArena();
}
inline void EthereumTokenInfo::set_address(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  address_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.address)
}
inline void EthereumTokenInfo::set_address(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  address_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.address)
}
inline void EthereumTokenInfo::set_address(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  address_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.address)
}
inline void EthereumTokenInfo::set_address(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  address_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.address)
}
inline std::string* EthereumTokenInfo::mutable_address() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.address)
  return address_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* EthereumTokenInfo::release_address() {
  // @@protoc_insertion_point(field_release:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.address)
  if (!has_address()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return address_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void EthereumTokenInfo::set_allocated_address(std::string* address) {
  if (address != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  address_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), address);
  // @@protoc_insertion_point(field_set_allocated:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.address)
}

// required uint64 chain_id = 2;
inline bool EthereumTokenInfo::has_chain_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void EthereumTokenInfo::clear_chain_id() {
  chain_id_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 EthereumTokenInfo::chain_id() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.chain_id)
  return chain_id_;
}
inline void EthereumTokenInfo::set_chain_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000008u;
  chain_id_ = value;
  // @@protoc_insertion_point(field_set:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.chain_id)
}

// required string symbol = 3;
inline bool EthereumTokenInfo::has_symbol() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void EthereumTokenInfo::clear_symbol() {
  symbol_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& EthereumTokenInfo::symbol() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.symbol)
  return symbol_.GetNoArena();
}
inline void EthereumTokenInfo::set_symbol(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  symbol_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.symbol)
}
inline void EthereumTokenInfo::set_symbol(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  symbol_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.symbol)
}
inline void EthereumTokenInfo::set_symbol(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  symbol_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.symbol)
}
inline void EthereumTokenInfo::set_symbol(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  symbol_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.symbol)
}
inline std::string* EthereumTokenInfo::mutable_symbol() {
  _has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_mutable:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.symbol)
  return symbol_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* EthereumTokenInfo::release_symbol() {
  // @@protoc_insertion_point(field_release:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.symbol)
  if (!has_symbol()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return symbol_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void EthereumTokenInfo::set_allocated_symbol(std::string* symbol) {
  if (symbol != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  symbol_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), symbol);
  // @@protoc_insertion_point(field_set_allocated:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.symbol)
}

// required uint32 decimals = 4;
inline bool EthereumTokenInfo::has_decimals() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void EthereumTokenInfo::clear_decimals() {
  decimals_ = 0u;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 EthereumTokenInfo::decimals() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.decimals)
  return decimals_;
}
inline void EthereumTokenInfo::set_decimals(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000010u;
  decimals_ = value;
  // @@protoc_insertion_point(field_set:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.decimals)
}

// required string name = 5;
inline bool EthereumTokenInfo::has_name() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void EthereumTokenInfo::clear_name() {
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& EthereumTokenInfo::name() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.name)
  return name_.GetNoArena();
}
inline void EthereumTokenInfo::set_name(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.name)
}
inline void EthereumTokenInfo::set_name(std::string&& value) {
  _has_bits_[0] |= 0x00000004u;
  name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.name)
}
inline void EthereumTokenInfo::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000004u;
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.name)
}
inline void EthereumTokenInfo::set_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000004u;
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.name)
}
inline std::string* EthereumTokenInfo::mutable_name() {
  _has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_mutable:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.name)
  return name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* EthereumTokenInfo::release_name() {
  // @@protoc_insertion_point(field_release:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.name)
  if (!has_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return name_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void EthereumTokenInfo::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:hw.trezor.messages.ethereum_definitions.EthereumTokenInfo.name)
}

// -------------------------------------------------------------------

// EthereumDefinitions

// optional bytes encoded_network = 1;
inline bool EthereumDefinitions::has_encoded_network() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void EthereumDefinitions::clear_encoded_network() {
  encoded_network_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& EthereumDefinitions::encoded_network() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.ethereum_definitions.EthereumDefinitions.encoded_network)
  return encoded_network_.GetNoArena();
}
inline void EthereumDefinitions::set_encoded_network(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  encoded_network_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hw.trezor.messages.ethereum_definitions.EthereumDefinitions.encoded_network)
}
inline void EthereumDefinitions::set_encoded_network(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  encoded_network_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hw.trezor.messages.ethereum_definitions.EthereumDefinitions.encoded_network)
}
inline void EthereumDefinitions::set_encoded_network(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  encoded_network_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hw.trezor.messages.ethereum_definitions.EthereumDefinitions.encoded_network)
}
inline void EthereumDefinitions::set_encoded_network(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  encoded_network_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hw.trezor.messages.ethereum_definitions.EthereumDefinitions.encoded_network)
}
inline std::string* EthereumDefinitions::mutable_encoded_network() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:hw.trezor.messages.ethereum_definitions.EthereumDefinitions.encoded_network)
  return encoded_network_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* EthereumDefinitions::release_encoded_network() {
  // @@protoc_insertion_point(field_release:hw.trezor.messages.ethereum_definitions.EthereumDefinitions.encoded_network)
  if (!has_encoded_network()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return encoded_network_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void EthereumDefinitions::set_allocated_encoded_network(std::string* encoded_network) {
  if (encoded_network != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  encoded_network_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), encoded_network);
  // @@protoc_insertion_point(field_set_allocated:hw.trezor.messages.ethereum_definitions.EthereumDefinitions.encoded_network)
}

// optional bytes encoded_token = 2;
inline bool EthereumDefinitions::has_encoded_token() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void EthereumDefinitions::clear_encoded_token() {
  encoded_token_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& EthereumDefinitions::encoded_token() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.ethereum_definitions.EthereumDefinitions.encoded_token)
  return encoded_token_.GetNoArena();
}
inline void EthereumDefinitions::set_encoded_token(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  encoded_token_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hw.trezor.messages.ethereum_definitions.EthereumDefinitions.encoded_token)
}
inline void EthereumDefinitions::set_encoded_token(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  encoded_token_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hw.trezor.messages.ethereum_definitions.EthereumDefinitions.encoded_token)
}
inline void EthereumDefinitions::set_encoded_token(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  encoded_token_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hw.trezor.messages.ethereum_definitions.EthereumDefinitions.encoded_token)
}
inline void EthereumDefinitions::set_encoded_token(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  encoded_token_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hw.trezor.messages.ethereum_definitions.EthereumDefinitions.encoded_token)
}
inline std::string* EthereumDefinitions::mutable_encoded_token() {
  _has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_mutable:hw.trezor.messages.ethereum_definitions.EthereumDefinitions.encoded_token)
  return encoded_token_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* EthereumDefinitions::release_encoded_token() {
  // @@protoc_insertion_point(field_release:hw.trezor.messages.ethereum_definitions.EthereumDefinitions.encoded_token)
  if (!has_encoded_token()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return encoded_token_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void EthereumDefinitions::set_allocated_encoded_token(std::string* encoded_token) {
  if (encoded_token != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  encoded_token_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), encoded_token);
  // @@protoc_insertion_point(field_set_allocated:hw.trezor.messages.ethereum_definitions.EthereumDefinitions.encoded_token)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ethereum_definitions
}  // namespace messages
}  // namespace trezor
}  // namespace hw

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::hw::trezor::messages::ethereum_definitions::EthereumDefinitionType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::hw::trezor::messages::ethereum_definitions::EthereumDefinitionType>() {
  return ::hw::trezor::messages::ethereum_definitions::EthereumDefinitionType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_messages_2dethereum_2ddefinitions_2eproto
