/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_HW_TREZOR_MESSAGES_COMMON_MESSAGES_COMMON_PB_H_INCLUDED
#define PB_HW_TREZOR_MESSAGES_COMMON_MESSAGES_COMMON_PB_H_INCLUDED
#include "pb.h"
#include "messages.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _FailureType {
    FailureType_Failure_UnexpectedMessage = 1,
    FailureType_Failure_ButtonExpected = 2,
    FailureType_Failure_DataError = 3,
    FailureType_Failure_ActionCancelled = 4,
    FailureType_Failure_PinExpected = 5,
    FailureType_Failure_PinCancelled = 6,
    FailureType_Failure_PinInvalid = 7,
    FailureType_Failure_InvalidSignature = 8,
    FailureType_Failure_ProcessError = 9,
    FailureType_Failure_NotEnoughFunds = 10,
    FailureType_Failure_NotInitialized = 11,
    FailureType_Failure_PinMismatch = 12,
    FailureType_Failure_WipeCodeMismatch = 13,
    FailureType_Failure_InvalidSession = 14,
    FailureType_Failure_FirmwareError = 99
} FailureType;

typedef enum _ButtonRequestType {
    ButtonRequestType_ButtonRequest_Other = 1,
    ButtonRequestType_ButtonRequest_FeeOverThreshold = 2,
    ButtonRequestType_ButtonRequest_ConfirmOutput = 3,
    ButtonRequestType_ButtonRequest_ResetDevice = 4,
    ButtonRequestType_ButtonRequest_ConfirmWord = 5,
    ButtonRequestType_ButtonRequest_WipeDevice = 6,
    ButtonRequestType_ButtonRequest_ProtectCall = 7,
    ButtonRequestType_ButtonRequest_SignTx = 8,
    ButtonRequestType_ButtonRequest_FirmwareCheck = 9,
    ButtonRequestType_ButtonRequest_Address = 10,
    ButtonRequestType_ButtonRequest_PublicKey = 11,
    ButtonRequestType_ButtonRequest_MnemonicWordCount = 12,
    ButtonRequestType_ButtonRequest_MnemonicInput = 13,
    ButtonRequestType__Deprecated_ButtonRequest_PassphraseType = 14,
    ButtonRequestType_ButtonRequest_UnknownDerivationPath = 15,
    ButtonRequestType_ButtonRequest_RecoveryHomepage = 16,
    ButtonRequestType_ButtonRequest_Success = 17,
    ButtonRequestType_ButtonRequest_Warning = 18,
    ButtonRequestType_ButtonRequest_PassphraseEntry = 19,
    ButtonRequestType_ButtonRequest_PinEntry = 20,
    ButtonRequestType_ButtonRequest_IrisEntry = 21
} ButtonRequestType;

typedef enum _PinMatrixRequestType {
    PinMatrixRequestType_PinMatrixRequestType_Current = 1,
    PinMatrixRequestType_PinMatrixRequestType_NewFirst = 2,
    PinMatrixRequestType_PinMatrixRequestType_NewSecond = 3,
    PinMatrixRequestType_PinMatrixRequestType_WipeCodeFirst = 4,
    PinMatrixRequestType_PinMatrixRequestType_WipeCodeSecond = 5
} PinMatrixRequestType;

/* Struct definitions */
typedef struct _Success {
    bool has_message;
    char message[256];
} Success;

typedef struct _Failure {
    bool has_code;
    FailureType code;
    bool has_message;
    char message[256];
} Failure;

typedef struct _ButtonRequest {
    bool has_code;
    ButtonRequestType code;
    bool has_pages;
    uint32_t pages;
} ButtonRequest;

typedef struct _ButtonAck {
    char dummy_field;
} ButtonAck;

typedef struct _PinMatrixRequest {
    bool has_type;
    PinMatrixRequestType type;
} PinMatrixRequest;

typedef struct _PinMatrixAck {
    pb_callback_t pin;
} PinMatrixAck;

typedef struct _PassphraseRequest {
    bool has__on_device;
    bool _on_device;
} PassphraseRequest;

typedef struct _PassphraseAck {
    pb_callback_t passphrase;
    pb_callback_t _state;
    bool has_on_device;
    bool on_device;
} PassphraseAck;

typedef struct _Deprecated_PassphraseStateRequest {
    pb_callback_t state;
} Deprecated_PassphraseStateRequest;

typedef struct _Deprecated_PassphraseStateAck {
    char dummy_field;
} Deprecated_PassphraseStateAck;

typedef struct _HDNodeType {
    uint32_t depth;
    uint32_t fingerprint;
    uint32_t child_num;
    pb_callback_t chain_code;
    pb_callback_t private_key;
    pb_callback_t public_key;
} HDNodeType;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _FailureType_MIN FailureType_Failure_UnexpectedMessage
#define _FailureType_MAX FailureType_Failure_FirmwareError
#define _FailureType_ARRAYSIZE ((FailureType)(FailureType_Failure_FirmwareError+1))

#define _ButtonRequestType_MIN ButtonRequestType_ButtonRequest_Other
#define _ButtonRequestType_MAX ButtonRequestType_ButtonRequest_IrisEntry
#define _ButtonRequestType_ARRAYSIZE ((ButtonRequestType)(ButtonRequestType_ButtonRequest_IrisEntry+1))

#define _PinMatrixRequestType_MIN PinMatrixRequestType_PinMatrixRequestType_Current
#define _PinMatrixRequestType_MAX PinMatrixRequestType_PinMatrixRequestType_WipeCodeSecond
#define _PinMatrixRequestType_ARRAYSIZE ((PinMatrixRequestType)(PinMatrixRequestType_PinMatrixRequestType_WipeCodeSecond+1))


#define Failure_code_ENUMTYPE FailureType

#define ButtonRequest_code_ENUMTYPE ButtonRequestType


#define PinMatrixRequest_type_ENUMTYPE PinMatrixRequestType








/* Initializer values for message structs */
#define Success_init_default                     {false, ""}
#define Failure_init_default                     {false, _FailureType_MIN, false, ""}
#define ButtonRequest_init_default               {false, _ButtonRequestType_MIN, false, 0}
#define ButtonAck_init_default                   {0}
#define PinMatrixRequest_init_default            {false, _PinMatrixRequestType_MIN}
#define PinMatrixAck_init_default                {{{NULL}, NULL}}
#define PassphraseRequest_init_default           {false, 0}
#define PassphraseAck_init_default               {{{NULL}, NULL}, {{NULL}, NULL}, false, 0}
#define Deprecated_PassphraseStateRequest_init_default {{{NULL}, NULL}}
#define Deprecated_PassphraseStateAck_init_default {0}
#define HDNodeType_init_default                  {0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define Success_init_zero                        {false, ""}
#define Failure_init_zero                        {false, _FailureType_MIN, false, ""}
#define ButtonRequest_init_zero                  {false, _ButtonRequestType_MIN, false, 0}
#define ButtonAck_init_zero                      {0}
#define PinMatrixRequest_init_zero               {false, _PinMatrixRequestType_MIN}
#define PinMatrixAck_init_zero                   {{{NULL}, NULL}}
#define PassphraseRequest_init_zero              {false, 0}
#define PassphraseAck_init_zero                  {{{NULL}, NULL}, {{NULL}, NULL}, false, 0}
#define Deprecated_PassphraseStateRequest_init_zero {{{NULL}, NULL}}
#define Deprecated_PassphraseStateAck_init_zero  {0}
#define HDNodeType_init_zero                     {0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define Success_message_tag                      1
#define Failure_code_tag                         1
#define Failure_message_tag                      2
#define ButtonRequest_code_tag                   1
#define ButtonRequest_pages_tag                  2
#define PinMatrixRequest_type_tag                1
#define PinMatrixAck_pin_tag                     1
#define PassphraseRequest__on_device_tag         1
#define PassphraseAck_passphrase_tag             1
#define PassphraseAck__state_tag                 2
#define PassphraseAck_on_device_tag              3
#define Deprecated_PassphraseStateRequest_state_tag 1
#define HDNodeType_depth_tag                     1
#define HDNodeType_fingerprint_tag               2
#define HDNodeType_child_num_tag                 3
#define HDNodeType_chain_code_tag                4
#define HDNodeType_private_key_tag               5
#define HDNodeType_public_key_tag                6

/* Struct field encoding specification for nanopb */
#define Success_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   message,           1)
#define Success_CALLBACK NULL
#define Success_DEFAULT (const pb_byte_t*)"\x0a\x00\x00"

#define Failure_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    code,              1) \
X(a, STATIC,   OPTIONAL, STRING,   message,           2)
#define Failure_CALLBACK NULL
#define Failure_DEFAULT (const pb_byte_t*)"\x08\x01\x00"

#define ButtonRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    code,              1) \
X(a, STATIC,   OPTIONAL, UINT32,   pages,             2)
#define ButtonRequest_CALLBACK NULL
#define ButtonRequest_DEFAULT (const pb_byte_t*)"\x08\x01\x00"

#define ButtonAck_FIELDLIST(X, a) \

#define ButtonAck_CALLBACK NULL
#define ButtonAck_DEFAULT NULL

#define PinMatrixRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    type,              1)
#define PinMatrixRequest_CALLBACK NULL
#define PinMatrixRequest_DEFAULT (const pb_byte_t*)"\x08\x01\x00"

#define PinMatrixAck_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   pin,               1)
#define PinMatrixAck_CALLBACK pb_default_field_callback
#define PinMatrixAck_DEFAULT NULL

#define PassphraseRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     _on_device,        1)
#define PassphraseRequest_CALLBACK NULL
#define PassphraseRequest_DEFAULT NULL

#define PassphraseAck_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   passphrase,        1) \
X(a, CALLBACK, OPTIONAL, BYTES,    _state,            2) \
X(a, STATIC,   OPTIONAL, BOOL,     on_device,         3)
#define PassphraseAck_CALLBACK pb_default_field_callback
#define PassphraseAck_DEFAULT NULL

#define Deprecated_PassphraseStateRequest_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, BYTES,    state,             1)
#define Deprecated_PassphraseStateRequest_CALLBACK pb_default_field_callback
#define Deprecated_PassphraseStateRequest_DEFAULT NULL

#define Deprecated_PassphraseStateAck_FIELDLIST(X, a) \

#define Deprecated_PassphraseStateAck_CALLBACK NULL
#define Deprecated_PassphraseStateAck_DEFAULT NULL

#define HDNodeType_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   depth,             1) \
X(a, STATIC,   REQUIRED, UINT32,   fingerprint,       2) \
X(a, STATIC,   REQUIRED, UINT32,   child_num,         3) \
X(a, CALLBACK, REQUIRED, BYTES,    chain_code,        4) \
X(a, CALLBACK, OPTIONAL, BYTES,    private_key,       5) \
X(a, CALLBACK, REQUIRED, BYTES,    public_key,        6)
#define HDNodeType_CALLBACK pb_default_field_callback
#define HDNodeType_DEFAULT NULL

extern const pb_msgdesc_t Success_msg;
extern const pb_msgdesc_t Failure_msg;
extern const pb_msgdesc_t ButtonRequest_msg;
extern const pb_msgdesc_t ButtonAck_msg;
extern const pb_msgdesc_t PinMatrixRequest_msg;
extern const pb_msgdesc_t PinMatrixAck_msg;
extern const pb_msgdesc_t PassphraseRequest_msg;
extern const pb_msgdesc_t PassphraseAck_msg;
extern const pb_msgdesc_t Deprecated_PassphraseStateRequest_msg;
extern const pb_msgdesc_t Deprecated_PassphraseStateAck_msg;
extern const pb_msgdesc_t HDNodeType_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Success_fields &Success_msg
#define Failure_fields &Failure_msg
#define ButtonRequest_fields &ButtonRequest_msg
#define ButtonAck_fields &ButtonAck_msg
#define PinMatrixRequest_fields &PinMatrixRequest_msg
#define PinMatrixAck_fields &PinMatrixAck_msg
#define PassphraseRequest_fields &PassphraseRequest_msg
#define PassphraseAck_fields &PassphraseAck_msg
#define Deprecated_PassphraseStateRequest_fields &Deprecated_PassphraseStateRequest_msg
#define Deprecated_PassphraseStateAck_fields &Deprecated_PassphraseStateAck_msg
#define HDNodeType_fields &HDNodeType_msg

/* Maximum encoded size of messages (where known) */
/* PinMatrixAck_size depends on runtime parameters */
/* PassphraseAck_size depends on runtime parameters */
/* Deprecated_PassphraseStateRequest_size depends on runtime parameters */
/* HDNodeType_size depends on runtime parameters */
#define ButtonAck_size                           0
#define ButtonRequest_size                       8
#define Deprecated_PassphraseStateAck_size       0
#define Failure_size                             260
#define HW_TREZOR_MESSAGES_COMMON_MESSAGES_COMMON_PB_H_MAX_SIZE Failure_size
#define PassphraseRequest_size                   2
#define PinMatrixRequest_size                    2
#define Success_size                             258

/* Mapping from canonical names (mangle_names or overridden package name) */
#define hw_trezor_messages_common_Success Success
#define hw_trezor_messages_common_Failure Failure
#define hw_trezor_messages_common_Failure_FailureType FailureType
#define hw_trezor_messages_common_ButtonRequest ButtonRequest
#define hw_trezor_messages_common_ButtonRequest_ButtonRequestType ButtonRequestType
#define hw_trezor_messages_common_ButtonAck ButtonAck
#define hw_trezor_messages_common_PinMatrixRequest PinMatrixRequest
#define hw_trezor_messages_common_PinMatrixRequest_PinMatrixRequestType PinMatrixRequestType
#define hw_trezor_messages_common_PinMatrixAck PinMatrixAck
#define hw_trezor_messages_common_PassphraseRequest PassphraseRequest
#define hw_trezor_messages_common_PassphraseAck PassphraseAck
#define hw_trezor_messages_common_Deprecated_PassphraseStateRequest Deprecated_PassphraseStateRequest
#define hw_trezor_messages_common_Deprecated_PassphraseStateAck Deprecated_PassphraseStateAck
#define hw_trezor_messages_common_HDNodeType HDNodeType
#define _hw_trezor_messages_common_Failure_FailureType_MIN _FailureType_MIN
#define _hw_trezor_messages_common_Failure_FailureType_MAX _FailureType_MAX
#define _hw_trezor_messages_common_Failure_FailureType_ARRAYSIZE _FailureType_ARRAYSIZE
#define _hw_trezor_messages_common_ButtonRequest_ButtonRequestType_MIN _ButtonRequestType_MIN
#define _hw_trezor_messages_common_ButtonRequest_ButtonRequestType_MAX _ButtonRequestType_MAX
#define _hw_trezor_messages_common_ButtonRequest_ButtonRequestType_ARRAYSIZE _ButtonRequestType_ARRAYSIZE
#define _hw_trezor_messages_common_PinMatrixRequest_PinMatrixRequestType_MIN _PinMatrixRequestType_MIN
#define _hw_trezor_messages_common_PinMatrixRequest_PinMatrixRequestType_MAX _PinMatrixRequestType_MAX
#define _hw_trezor_messages_common_PinMatrixRequest_PinMatrixRequestType_ARRAYSIZE _PinMatrixRequestType_ARRAYSIZE
#define hw_trezor_messages_common_Success_init_default Success_init_default
#define hw_trezor_messages_common_Failure_init_default Failure_init_default
#define hw_trezor_messages_common_ButtonRequest_init_default ButtonRequest_init_default
#define hw_trezor_messages_common_ButtonAck_init_default ButtonAck_init_default
#define hw_trezor_messages_common_PinMatrixRequest_init_default PinMatrixRequest_init_default
#define hw_trezor_messages_common_PinMatrixAck_init_default PinMatrixAck_init_default
#define hw_trezor_messages_common_PassphraseRequest_init_default PassphraseRequest_init_default
#define hw_trezor_messages_common_PassphraseAck_init_default PassphraseAck_init_default
#define hw_trezor_messages_common_Deprecated_PassphraseStateRequest_init_default Deprecated_PassphraseStateRequest_init_default
#define hw_trezor_messages_common_Deprecated_PassphraseStateAck_init_default Deprecated_PassphraseStateAck_init_default
#define hw_trezor_messages_common_HDNodeType_init_default HDNodeType_init_default
#define hw_trezor_messages_common_Success_init_zero Success_init_zero
#define hw_trezor_messages_common_Failure_init_zero Failure_init_zero
#define hw_trezor_messages_common_ButtonRequest_init_zero ButtonRequest_init_zero
#define hw_trezor_messages_common_ButtonAck_init_zero ButtonAck_init_zero
#define hw_trezor_messages_common_PinMatrixRequest_init_zero PinMatrixRequest_init_zero
#define hw_trezor_messages_common_PinMatrixAck_init_zero PinMatrixAck_init_zero
#define hw_trezor_messages_common_PassphraseRequest_init_zero PassphraseRequest_init_zero
#define hw_trezor_messages_common_PassphraseAck_init_zero PassphraseAck_init_zero
#define hw_trezor_messages_common_Deprecated_PassphraseStateRequest_init_zero Deprecated_PassphraseStateRequest_init_zero
#define hw_trezor_messages_common_Deprecated_PassphraseStateAck_init_zero Deprecated_PassphraseStateAck_init_zero
#define hw_trezor_messages_common_HDNodeType_init_zero HDNodeType_init_zero

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
