/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_HW_TREZOR_MESSAGES_MANAGEMENT_MESSAGES_MANAGEMENT_PB_H_INCLUDED
#define PB_HW_TREZOR_MESSAGES_MANAGEMENT_MESSAGES_MANAGEMENT_PB_H_INCLUDED
#include "pb.h"
#include "messages.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _BackupType {
    BackupType_Bip39 = 0,
    BackupType_Slip39_Basic = 1,
    BackupType_Slip39_Advanced = 2
} BackupType;

typedef enum _SafetyCheckLevel {
    SafetyCheckLevel_Strict = 0,
    SafetyCheckLevel_PromptAlways = 1,
    SafetyCheckLevel_PromptTemporarily = 2
} SafetyCheckLevel;

typedef enum _Capability {
    Capability_Capability_Bitcoin = 1,
    Capability_Capability_Bitcoin_like = 2,
    Capability_Capability_Binance = 3,
    Capability_Capability_Cardano = 4,
    Capability_Capability_Crypto = 5,
    Capability_Capability_EOS = 6,
    Capability_Capability_Ethereum = 7,
    Capability_Capability_Lisk = 8,
    Capability_Capability_Monero = 9,
    Capability_Capability_NEM = 10,
    Capability_Capability_Ripple = 11,
    Capability_Capability_Stellar = 12,
    Capability_Capability_Tezos = 13,
    Capability_Capability_U2F = 14,
    Capability_Capability_Shamir = 15,
    Capability_Capability_ShamirGroups = 16,
    Capability_Capability_PassphraseEntry = 17
} Capability;

typedef enum _SdProtectOperationType {
    SdProtectOperationType_DISABLE = 0,
    SdProtectOperationType_ENABLE = 1,
    SdProtectOperationType_REFRESH = 2
} SdProtectOperationType;

typedef enum _RecoveryDeviceType {
    RecoveryDeviceType_RecoveryDeviceType_ScrambledWords = 0,
    RecoveryDeviceType_RecoveryDeviceType_Matrix = 1
} RecoveryDeviceType;

typedef enum _WordRequestType {
    WordRequestType_WordRequestType_Plain = 0,
    WordRequestType_WordRequestType_Matrix9 = 1,
    WordRequestType_WordRequestType_Matrix6 = 2
} WordRequestType;

typedef enum _ResourceType {
    ResourceType_WallPaper = 0,
    ResourceType_Nft = 1
} ResourceType;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(32) Initialize_session_id_t;
typedef struct _Initialize {
    bool has_session_id;
    Initialize_session_id_t session_id;
    bool has__skip_passphrase;
    bool _skip_passphrase;
    bool has_derive_cardano;
    bool derive_cardano;
} Initialize;

typedef struct _GetFeatures {
    char dummy_field;
} GetFeatures;

typedef PB_BYTES_ARRAY_T(20) Features_revision_t;
typedef PB_BYTES_ARRAY_T(32) Features_bootloader_hash_t;
typedef PB_BYTES_ARRAY_T(32) Features_session_id_t;
typedef PB_BYTES_ARRAY_T(32) Features_NFT_voucher_t;
typedef PB_BYTES_ARRAY_T(32) Features_build_id_t;
typedef struct _Features {
    bool has_vendor;
    char vendor[33];
    uint32_t major_version;
    uint32_t minor_version;
    uint32_t patch_version;
    bool has_bootloader_mode;
    bool bootloader_mode;
    bool has_device_id;
    char device_id[25];
    bool has_pin_protection;
    bool pin_protection;
    bool has_passphrase_protection;
    bool passphrase_protection;
    bool has_language;
    char language[17];
    bool has_label;
    char label[33];
    bool has_initialized;
    bool initialized;
    bool has_revision;
    Features_revision_t revision;
    bool has_bootloader_hash;
    Features_bootloader_hash_t bootloader_hash;
    bool has_imported;
    bool imported;
    bool has_unlocked;
    bool unlocked;
    bool has__passphrase_cached;
    bool _passphrase_cached;
    bool has_firmware_present;
    bool firmware_present;
    bool has_needs_backup;
    bool needs_backup;
    bool has_flags;
    uint32_t flags;
    bool has_model;
    char model[17];
    bool has_fw_major;
    uint32_t fw_major;
    bool has_fw_minor;
    uint32_t fw_minor;
    bool has_fw_patch;
    uint32_t fw_patch;
    bool has_fw_vendor;
    char fw_vendor[256];
    bool has_unfinished_backup;
    bool unfinished_backup;
    bool has_no_backup;
    bool no_backup;
    bool has_recovery_mode;
    bool recovery_mode;
    pb_size_t capabilities_count;
    Capability capabilities[32];
    bool has_backup_type;
    BackupType backup_type;
    bool has_sd_card_present;
    bool sd_card_present;
    bool has_sd_protection;
    bool sd_protection;
    bool has_wipe_code_protection;
    bool wipe_code_protection;
    bool has_session_id;
    Features_session_id_t session_id;
    bool has_passphrase_always_on_device;
    bool passphrase_always_on_device;
    bool has_safety_checks;
    SafetyCheckLevel safety_checks;
    bool has_auto_lock_delay_ms;
    uint32_t auto_lock_delay_ms;
    bool has_display_rotation;
    uint32_t display_rotation;
    bool has_experimental_features;
    bool experimental_features;
    bool has_busy;
    bool busy;
    bool has_offset;
    uint32_t offset;
    bool has_ble_name;
    char ble_name[32];
    bool has_ble_ver;
    char ble_ver[16];
    bool has_ble_enable;
    bool ble_enable;
    bool has_se_enable;
    bool se_enable;
    bool has_se_ver;
    char se_ver[16];
    bool has_backup_only;
    bool backup_only;
    bool has_hypermate_version;
    char hypermate_version[16];
    bool has_hypermate_serial;
    char hypermate_serial[32];
    bool has_bootloader_version;
    char bootloader_version[32];
    bool has_serial_no;
    char serial_no[32];
    bool has_spi_flash;
    char spi_flash[32];
    bool has_initstates;
    uint32_t initstates;
    bool has_NFT_voucher;
    Features_NFT_voucher_t NFT_voucher;
    bool has_cpu_info;
    char cpu_info[16];
    bool has_pre_firmware;
    char pre_firmware[16];
    bool has_coin_switch;
    uint32_t coin_switch;
    bool has_build_id;
    Features_build_id_t build_id;
    bool has_boardloader_version;
    char boardloader_version[16];
    bool has_iris_version;
    char iris_version[16];
    bool has_battery;
    uint32_t battery;
} Features;

typedef struct _LockDevice {
    char dummy_field;
} LockDevice;

typedef struct _SetBusy {
    bool has_expiry_ms;
    uint32_t expiry_ms;
} SetBusy;

typedef struct _EndSession {
    char dummy_field;
} EndSession;

typedef struct _ApplySettings {
    pb_callback_t language;
    pb_callback_t label;
    bool has_use_passphrase;
    bool use_passphrase;
    pb_callback_t homescreen;
    bool has__passphrase_source;
    uint32_t _passphrase_source;
    bool has_auto_lock_delay_ms;
    uint32_t auto_lock_delay_ms;
    bool has_display_rotation;
    uint32_t display_rotation;
    bool has_passphrase_always_on_device;
    bool passphrase_always_on_device;
    bool has_safety_checks;
    SafetyCheckLevel safety_checks;
    bool has_experimental_features;
    bool experimental_features;
} ApplySettings;

typedef struct _ApplyFlags {
    uint32_t flags;
} ApplyFlags;

typedef struct _ChangePin {
    bool has_remove;
    bool remove;
} ChangePin;

typedef struct _ChangeWipeCode {
    bool has_remove;
    bool remove;
} ChangeWipeCode;

typedef struct _SdProtect {
    SdProtectOperationType operation;
} SdProtect;

typedef struct _Ping {
    bool has_message;
    char message[256];
    bool has_button_protection;
    bool button_protection;
} Ping;

typedef struct _Cancel {
    char dummy_field;
} Cancel;

typedef struct _GetEntropy {
    uint32_t size;
} GetEntropy;

typedef struct _Entropy {
    pb_callback_t entropy;
} Entropy;

typedef struct _GetFirmwareHash {
    pb_callback_t challenge;
} GetFirmwareHash;

typedef struct _FirmwareHash {
    pb_callback_t hash;
} FirmwareHash;

typedef struct _WipeDevice {
    char dummy_field;
} WipeDevice;

typedef struct _LoadDevice {
    pb_callback_t mnemonics;
    pb_callback_t pin;
    bool has_passphrase_protection;
    bool passphrase_protection;
    pb_callback_t language;
    pb_callback_t label;
    bool has_skip_checksum;
    bool skip_checksum;
    bool has_u2f_counter;
    uint32_t u2f_counter;
    bool has_needs_backup;
    bool needs_backup;
    bool has_no_backup;
    bool no_backup;
} LoadDevice;

typedef struct _ResetDevice {
    bool has_display_random;
    bool display_random;
    bool has_strength;
    uint32_t strength;
    bool has_passphrase_protection;
    bool passphrase_protection;
    bool has_pin_protection;
    bool pin_protection;
    pb_callback_t language;
    pb_callback_t label;
    bool has_u2f_counter;
    uint32_t u2f_counter;
    bool has_skip_backup;
    bool skip_backup;
    bool has_no_backup;
    bool no_backup;
    bool has_backup_type;
    BackupType backup_type;
} ResetDevice;

typedef struct _BackupDevice {
    char dummy_field;
} BackupDevice;

typedef struct _EntropyRequest {
    char dummy_field;
} EntropyRequest;

typedef struct _EntropyAck {
    pb_callback_t entropy;
} EntropyAck;

typedef struct _RecoveryDevice {
    bool has_word_count;
    uint32_t word_count;
    bool has_passphrase_protection;
    bool passphrase_protection;
    bool has_pin_protection;
    bool pin_protection;
    pb_callback_t language;
    pb_callback_t label;
    bool has_enforce_wordlist;
    bool enforce_wordlist;
    bool has_type;
    RecoveryDeviceType type;
    bool has_u2f_counter;
    uint32_t u2f_counter;
    bool has_dry_run;
    bool dry_run;
} RecoveryDevice;

typedef struct _WordRequest {
    WordRequestType type;
} WordRequest;

typedef struct _WordAck {
    pb_callback_t word;
} WordAck;

typedef struct _SetU2FCounter {
    uint32_t u2f_counter;
} SetU2FCounter;

typedef struct _GetNextU2FCounter {
    char dummy_field;
} GetNextU2FCounter;

typedef struct _NextU2FCounter {
    uint32_t u2f_counter;
} NextU2FCounter;

typedef struct _DoPreauthorized {
    char dummy_field;
} DoPreauthorized;

typedef struct _PreauthorizedRequest {
    char dummy_field;
} PreauthorizedRequest;

typedef struct _CancelAuthorization {
    char dummy_field;
} CancelAuthorization;

typedef struct _RebootToBootloader {
    char dummy_field;
} RebootToBootloader;

typedef struct _RebootToBoardloader {
    char dummy_field;
} RebootToBoardloader;

typedef struct _GetNonce {
    char dummy_field;
} GetNonce;

typedef struct _Nonce {
    pb_callback_t nonce;
} Nonce;

typedef struct _DeviceBackToBoot {
    char dummy_field;
} DeviceBackToBoot;

typedef struct _DeviceInfoSettings {
    bool has_serial_no;
    char serial_no[32];
    bool has_cpu_info;
    char cpu_info[16];
    bool has_pre_firmware;
    char pre_firmware[16];
} DeviceInfoSettings;

typedef struct _GetDeviceInfo {
    char dummy_field;
} GetDeviceInfo;

typedef struct _DeviceInfo {
    pb_callback_t serial_no;
    pb_callback_t spiFlash_info;
    pb_callback_t SE_info;
    pb_callback_t NFT_voucher;
    pb_callback_t cpu_info;
    pb_callback_t pre_firmware;
} DeviceInfo;

typedef struct _ReadSEPublicKey {
    char dummy_field;
} ReadSEPublicKey;

typedef PB_BYTES_ARRAY_T(65) SEPublicKey_public_key_t;
typedef struct _SEPublicKey {
    SEPublicKey_public_key_t public_key;
} SEPublicKey;

typedef PB_BYTES_ARRAY_T(1024) WriteSEPublicCert_public_cert_t;
typedef struct _WriteSEPublicCert {
    WriteSEPublicCert_public_cert_t public_cert;
} WriteSEPublicCert;

typedef struct _ReadSEPublicCert {
    char dummy_field;
} ReadSEPublicCert;

typedef PB_BYTES_ARRAY_T(1024) SEPublicCert_public_cert_t;
typedef struct _SEPublicCert {
    SEPublicCert_public_cert_t public_cert;
} SEPublicCert;

typedef PB_BYTES_ARRAY_T(512) SESignMessage_message_t;
typedef struct _SESignMessage {
    SESignMessage_message_t message;
} SESignMessage;

typedef PB_BYTES_ARRAY_T(64) SEMessageSignature_signature_t;
typedef struct _SEMessageSignature {
    SEMessageSignature_signature_t signature;
} SEMessageSignature;

typedef struct _SEInitialize {
    char dummy_field;
} SEInitialize;

typedef struct _SEInitializeDone {
    char dummy_field;
} SEInitializeDone;

typedef struct _SEBackToRomBoot {
    char dummy_field;
} SEBackToRomBoot;

typedef struct _SEWipeUserStorage {
    char dummy_field;
} SEWipeUserStorage;

typedef struct _ResourceUpload {
    pb_callback_t extension;
    uint32_t data_length;
    ResourceType res_type;
    pb_callback_t nft_meta_data;
    uint32_t zoom_data_length;
    pb_callback_t file_name_no_ext;
} ResourceUpload;

typedef struct _ZoomRequest {
    bool has_offset;
    uint32_t offset;
    uint32_t data_length;
} ZoomRequest;

typedef struct _ResourceRequest {
    bool has_offset;
    uint32_t offset;
    uint32_t data_length;
} ResourceRequest;

typedef struct _ResourceAck {
    pb_callback_t data_chunk;
    pb_callback_t hash;
} ResourceAck;

typedef struct _ResourceUpdate {
    pb_callback_t file_name;
    uint32_t data_length;
    pb_callback_t initial_data_chunk;
    pb_callback_t hash;
} ResourceUpdate;

typedef struct _ListResDir {
    pb_callback_t path;
} ListResDir;

typedef struct _FileInfoList {
    pb_callback_t files;
} FileInfoList;

typedef struct _FileInfo {
    pb_callback_t name;
    uint64_t size;
} FileInfo;

typedef struct _UnlockPath {
    pb_callback_t address_n;
    pb_callback_t mac;
} UnlockPath;

typedef struct _UnlockedPathRequest {
    pb_callback_t mac;
} UnlockedPathRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _BackupType_MIN BackupType_Bip39
#define _BackupType_MAX BackupType_Slip39_Advanced
#define _BackupType_ARRAYSIZE ((BackupType)(BackupType_Slip39_Advanced+1))

#define _SafetyCheckLevel_MIN SafetyCheckLevel_Strict
#define _SafetyCheckLevel_MAX SafetyCheckLevel_PromptTemporarily
#define _SafetyCheckLevel_ARRAYSIZE ((SafetyCheckLevel)(SafetyCheckLevel_PromptTemporarily+1))

#define _Capability_MIN Capability_Capability_Bitcoin
#define _Capability_MAX Capability_Capability_PassphraseEntry
#define _Capability_ARRAYSIZE ((Capability)(Capability_Capability_PassphraseEntry+1))

#define _SdProtectOperationType_MIN SdProtectOperationType_DISABLE
#define _SdProtectOperationType_MAX SdProtectOperationType_REFRESH
#define _SdProtectOperationType_ARRAYSIZE ((SdProtectOperationType)(SdProtectOperationType_REFRESH+1))

#define _RecoveryDeviceType_MIN RecoveryDeviceType_RecoveryDeviceType_ScrambledWords
#define _RecoveryDeviceType_MAX RecoveryDeviceType_RecoveryDeviceType_Matrix
#define _RecoveryDeviceType_ARRAYSIZE ((RecoveryDeviceType)(RecoveryDeviceType_RecoveryDeviceType_Matrix+1))

#define _WordRequestType_MIN WordRequestType_WordRequestType_Plain
#define _WordRequestType_MAX WordRequestType_WordRequestType_Matrix6
#define _WordRequestType_ARRAYSIZE ((WordRequestType)(WordRequestType_WordRequestType_Matrix6+1))

#define _ResourceType_MIN ResourceType_WallPaper
#define _ResourceType_MAX ResourceType_Nft
#define _ResourceType_ARRAYSIZE ((ResourceType)(ResourceType_Nft+1))



#define Features_capabilities_ENUMTYPE Capability
#define Features_backup_type_ENUMTYPE BackupType
#define Features_safety_checks_ENUMTYPE SafetyCheckLevel




#define ApplySettings_safety_checks_ENUMTYPE SafetyCheckLevel




#define SdProtect_operation_ENUMTYPE SdProtectOperationType









#define ResetDevice_backup_type_ENUMTYPE BackupType




#define RecoveryDevice_type_ENUMTYPE RecoveryDeviceType

#define WordRequest_type_ENUMTYPE WordRequestType



























#define ResourceUpload_res_type_ENUMTYPE ResourceType











/* Initializer values for message structs */
#define Initialize_init_default                  {false, {0, {0}}, false, 0, false, 0}
#define GetFeatures_init_default                 {0}
#define Features_init_default                    {false, "", 0, 0, 0, false, 0, false, "", false, 0, false, 0, false, "", false, "", false, 0, false, {0, {0}}, false, {0, {0}}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, "", false, 0, false, 0, false, 0, false, "", false, 0, false, 0, false, 0, 0, {_Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN}, false, _BackupType_MIN, false, 0, false, 0, false, 0, false, {0, {0}}, false, 0, false, _SafetyCheckLevel_MIN, false, 0, false, 0, false, 0, false, 0, false, 0, false, "", false, "", false, 0, false, 0, false, "", false, 0, false, "", false, "", false, "", false, "", false, "", false, 0, false, {0, {0}}, false, "", false, "", false, 0, false, {0, {0}}, false, "", false, "", false, 0}
#define LockDevice_init_default                  {0}
#define SetBusy_init_default                     {false, 0}
#define EndSession_init_default                  {0}
#define ApplySettings_init_default               {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, _SafetyCheckLevel_MIN, false, 0}
#define ApplyFlags_init_default                  {0}
#define ChangePin_init_default                   {false, 0}
#define ChangeWipeCode_init_default              {false, 0}
#define SdProtect_init_default                   {_SdProtectOperationType_MIN}
#define Ping_init_default                        {false, "", false, 0}
#define Cancel_init_default                      {0}
#define GetEntropy_init_default                  {0}
#define Entropy_init_default                     {{{NULL}, NULL}}
#define GetFirmwareHash_init_default             {{{NULL}, NULL}}
#define FirmwareHash_init_default                {{{NULL}, NULL}}
#define WipeDevice_init_default                  {0}
#define LoadDevice_init_default                  {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0}
#define ResetDevice_init_default                 {false, 0, false, 256u, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, BackupType_Bip39}
#define BackupDevice_init_default                {0}
#define EntropyRequest_init_default              {0}
#define EntropyAck_init_default                  {{{NULL}, NULL}}
#define RecoveryDevice_init_default              {false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, _RecoveryDeviceType_MIN, false, 0, false, 0}
#define WordRequest_init_default                 {_WordRequestType_MIN}
#define WordAck_init_default                     {{{NULL}, NULL}}
#define SetU2FCounter_init_default               {0}
#define GetNextU2FCounter_init_default           {0}
#define NextU2FCounter_init_default              {0}
#define DoPreauthorized_init_default             {0}
#define PreauthorizedRequest_init_default        {0}
#define CancelAuthorization_init_default         {0}
#define RebootToBootloader_init_default          {0}
#define RebootToBoardloader_init_default         {0}
#define GetNonce_init_default                    {0}
#define Nonce_init_default                       {{{NULL}, NULL}}
#define DeviceBackToBoot_init_default            {0}
#define DeviceInfoSettings_init_default          {false, "", false, "", false, ""}
#define GetDeviceInfo_init_default               {0}
#define DeviceInfo_init_default                  {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define ReadSEPublicKey_init_default             {0}
#define SEPublicKey_init_default                 {{0, {0}}}
#define WriteSEPublicCert_init_default           {{0, {0}}}
#define ReadSEPublicCert_init_default            {0}
#define SEPublicCert_init_default                {{0, {0}}}
#define SESignMessage_init_default               {{0, {0}}}
#define SEMessageSignature_init_default          {{0, {0}}}
#define SEInitialize_init_default                {0}
#define SEInitializeDone_init_default            {0}
#define SEBackToRomBoot_init_default             {0}
#define SEWipeUserStorage_init_default           {0}
#define ResourceUpload_init_default              {{{NULL}, NULL}, 0, _ResourceType_MIN, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define ZoomRequest_init_default                 {false, 0, 0}
#define ResourceRequest_init_default             {false, 0, 0}
#define ResourceAck_init_default                 {{{NULL}, NULL}, {{NULL}, NULL}}
#define ResourceUpdate_init_default              {{{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define ListResDir_init_default                  {{{NULL}, NULL}}
#define FileInfoList_init_default                {{{NULL}, NULL}}
#define FileInfo_init_default                    {{{NULL}, NULL}, 0}
#define UnlockPath_init_default                  {{{NULL}, NULL}, {{NULL}, NULL}}
#define UnlockedPathRequest_init_default         {{{NULL}, NULL}}
#define Initialize_init_zero                     {false, {0, {0}}, false, 0, false, 0}
#define GetFeatures_init_zero                    {0}
#define Features_init_zero                       {false, "", 0, 0, 0, false, 0, false, "", false, 0, false, 0, false, "", false, "", false, 0, false, {0, {0}}, false, {0, {0}}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, "", false, 0, false, 0, false, 0, false, "", false, 0, false, 0, false, 0, 0, {_Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN, _Capability_MIN}, false, _BackupType_MIN, false, 0, false, 0, false, 0, false, {0, {0}}, false, 0, false, _SafetyCheckLevel_MIN, false, 0, false, 0, false, 0, false, 0, false, 0, false, "", false, "", false, 0, false, 0, false, "", false, 0, false, "", false, "", false, "", false, "", false, "", false, 0, false, {0, {0}}, false, "", false, "", false, 0, false, {0, {0}}, false, "", false, "", false, 0}
#define LockDevice_init_zero                     {0}
#define SetBusy_init_zero                        {false, 0}
#define EndSession_init_zero                     {0}
#define ApplySettings_init_zero                  {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, _SafetyCheckLevel_MIN, false, 0}
#define ApplyFlags_init_zero                     {0}
#define ChangePin_init_zero                      {false, 0}
#define ChangeWipeCode_init_zero                 {false, 0}
#define SdProtect_init_zero                      {_SdProtectOperationType_MIN}
#define Ping_init_zero                           {false, "", false, 0}
#define Cancel_init_zero                         {0}
#define GetEntropy_init_zero                     {0}
#define Entropy_init_zero                        {{{NULL}, NULL}}
#define GetFirmwareHash_init_zero                {{{NULL}, NULL}}
#define FirmwareHash_init_zero                   {{{NULL}, NULL}}
#define WipeDevice_init_zero                     {0}
#define LoadDevice_init_zero                     {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0}
#define ResetDevice_init_zero                    {false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, _BackupType_MIN}
#define BackupDevice_init_zero                   {0}
#define EntropyRequest_init_zero                 {0}
#define EntropyAck_init_zero                     {{{NULL}, NULL}}
#define RecoveryDevice_init_zero                 {false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, _RecoveryDeviceType_MIN, false, 0, false, 0}
#define WordRequest_init_zero                    {_WordRequestType_MIN}
#define WordAck_init_zero                        {{{NULL}, NULL}}
#define SetU2FCounter_init_zero                  {0}
#define GetNextU2FCounter_init_zero              {0}
#define NextU2FCounter_init_zero                 {0}
#define DoPreauthorized_init_zero                {0}
#define PreauthorizedRequest_init_zero           {0}
#define CancelAuthorization_init_zero            {0}
#define RebootToBootloader_init_zero             {0}
#define RebootToBoardloader_init_zero            {0}
#define GetNonce_init_zero                       {0}
#define Nonce_init_zero                          {{{NULL}, NULL}}
#define DeviceBackToBoot_init_zero               {0}
#define DeviceInfoSettings_init_zero             {false, "", false, "", false, ""}
#define GetDeviceInfo_init_zero                  {0}
#define DeviceInfo_init_zero                     {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define ReadSEPublicKey_init_zero                {0}
#define SEPublicKey_init_zero                    {{0, {0}}}
#define WriteSEPublicCert_init_zero              {{0, {0}}}
#define ReadSEPublicCert_init_zero               {0}
#define SEPublicCert_init_zero                   {{0, {0}}}
#define SESignMessage_init_zero                  {{0, {0}}}
#define SEMessageSignature_init_zero             {{0, {0}}}
#define SEInitialize_init_zero                   {0}
#define SEInitializeDone_init_zero               {0}
#define SEBackToRomBoot_init_zero                {0}
#define SEWipeUserStorage_init_zero              {0}
#define ResourceUpload_init_zero                 {{{NULL}, NULL}, 0, _ResourceType_MIN, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define ZoomRequest_init_zero                    {false, 0, 0}
#define ResourceRequest_init_zero                {false, 0, 0}
#define ResourceAck_init_zero                    {{{NULL}, NULL}, {{NULL}, NULL}}
#define ResourceUpdate_init_zero                 {{{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define ListResDir_init_zero                     {{{NULL}, NULL}}
#define FileInfoList_init_zero                   {{{NULL}, NULL}}
#define FileInfo_init_zero                       {{{NULL}, NULL}, 0}
#define UnlockPath_init_zero                     {{{NULL}, NULL}, {{NULL}, NULL}}
#define UnlockedPathRequest_init_zero            {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define Initialize_session_id_tag                1
#define Initialize__skip_passphrase_tag          2
#define Initialize_derive_cardano_tag            3
#define Features_vendor_tag                      1
#define Features_major_version_tag               2
#define Features_minor_version_tag               3
#define Features_patch_version_tag               4
#define Features_bootloader_mode_tag             5
#define Features_device_id_tag                   6
#define Features_pin_protection_tag              7
#define Features_passphrase_protection_tag       8
#define Features_language_tag                    9
#define Features_label_tag                       10
#define Features_initialized_tag                 12
#define Features_revision_tag                    13
#define Features_bootloader_hash_tag             14
#define Features_imported_tag                    15
#define Features_unlocked_tag                    16
#define Features__passphrase_cached_tag          17
#define Features_firmware_present_tag            18
#define Features_needs_backup_tag                19
#define Features_flags_tag                       20
#define Features_model_tag                       21
#define Features_fw_major_tag                    22
#define Features_fw_minor_tag                    23
#define Features_fw_patch_tag                    24
#define Features_fw_vendor_tag                   25
#define Features_unfinished_backup_tag           27
#define Features_no_backup_tag                   28
#define Features_recovery_mode_tag               29
#define Features_capabilities_tag                30
#define Features_backup_type_tag                 31
#define Features_sd_card_present_tag             32
#define Features_sd_protection_tag               33
#define Features_wipe_code_protection_tag        34
#define Features_session_id_tag                  35
#define Features_passphrase_always_on_device_tag 36
#define Features_safety_checks_tag               37
#define Features_auto_lock_delay_ms_tag          38
#define Features_display_rotation_tag            39
#define Features_experimental_features_tag       40
#define Features_busy_tag                        41
#define Features_offset_tag                      500
#define Features_ble_name_tag                    501
#define Features_ble_ver_tag                     502
#define Features_ble_enable_tag                  503
#define Features_se_enable_tag                   504
#define Features_se_ver_tag                      506
#define Features_backup_only_tag                 507
#define Features_hypermate_version_tag           508
#define Features_hypermate_serial_tag            509
#define Features_bootloader_version_tag          510
#define Features_serial_no_tag                   511
#define Features_spi_flash_tag                   512
#define Features_initstates_tag                  513
#define Features_NFT_voucher_tag                 514
#define Features_cpu_info_tag                    515
#define Features_pre_firmware_tag                516
#define Features_coin_switch_tag                 517
#define Features_build_id_tag                    518
#define Features_boardloader_version_tag         519
#define Features_iris_version_tag                600
#define Features_battery_tag                     601
#define SetBusy_expiry_ms_tag                    1
#define ApplySettings_language_tag               1
#define ApplySettings_label_tag                  2
#define ApplySettings_use_passphrase_tag         3
#define ApplySettings_homescreen_tag             4
#define ApplySettings__passphrase_source_tag     5
#define ApplySettings_auto_lock_delay_ms_tag     6
#define ApplySettings_display_rotation_tag       7
#define ApplySettings_passphrase_always_on_device_tag 8
#define ApplySettings_safety_checks_tag          9
#define ApplySettings_experimental_features_tag  10
#define ApplyFlags_flags_tag                     1
#define ChangePin_remove_tag                     1
#define ChangeWipeCode_remove_tag                1
#define SdProtect_operation_tag                  1
#define Ping_message_tag                         1
#define Ping_button_protection_tag               2
#define GetEntropy_size_tag                      1
#define Entropy_entropy_tag                      1
#define GetFirmwareHash_challenge_tag            1
#define FirmwareHash_hash_tag                    1
#define LoadDevice_mnemonics_tag                 1
#define LoadDevice_pin_tag                       3
#define LoadDevice_passphrase_protection_tag     4
#define LoadDevice_language_tag                  5
#define LoadDevice_label_tag                     6
#define LoadDevice_skip_checksum_tag             7
#define LoadDevice_u2f_counter_tag               8
#define LoadDevice_needs_backup_tag              9
#define LoadDevice_no_backup_tag                 10
#define ResetDevice_display_random_tag           1
#define ResetDevice_strength_tag                 2
#define ResetDevice_passphrase_protection_tag    3
#define ResetDevice_pin_protection_tag           4
#define ResetDevice_language_tag                 5
#define ResetDevice_label_tag                    6
#define ResetDevice_u2f_counter_tag              7
#define ResetDevice_skip_backup_tag              8
#define ResetDevice_no_backup_tag                9
#define ResetDevice_backup_type_tag              10
#define EntropyAck_entropy_tag                   1
#define RecoveryDevice_word_count_tag            1
#define RecoveryDevice_passphrase_protection_tag 2
#define RecoveryDevice_pin_protection_tag        3
#define RecoveryDevice_language_tag              4
#define RecoveryDevice_label_tag                 5
#define RecoveryDevice_enforce_wordlist_tag      6
#define RecoveryDevice_type_tag                  8
#define RecoveryDevice_u2f_counter_tag           9
#define RecoveryDevice_dry_run_tag               10
#define WordRequest_type_tag                     1
#define WordAck_word_tag                         1
#define SetU2FCounter_u2f_counter_tag            1
#define NextU2FCounter_u2f_counter_tag           1
#define Nonce_nonce_tag                          1
#define DeviceInfoSettings_serial_no_tag         1
#define DeviceInfoSettings_cpu_info_tag          2
#define DeviceInfoSettings_pre_firmware_tag      3
#define DeviceInfo_serial_no_tag                 1
#define DeviceInfo_spiFlash_info_tag             2
#define DeviceInfo_SE_info_tag                   3
#define DeviceInfo_NFT_voucher_tag               4
#define DeviceInfo_cpu_info_tag                  5
#define DeviceInfo_pre_firmware_tag              6
#define SEPublicKey_public_key_tag               1
#define WriteSEPublicCert_public_cert_tag        1
#define SEPublicCert_public_cert_tag             1
#define SESignMessage_message_tag                1
#define SEMessageSignature_signature_tag         1
#define ResourceUpload_extension_tag             1
#define ResourceUpload_data_length_tag           2
#define ResourceUpload_res_type_tag              3
#define ResourceUpload_nft_meta_data_tag         4
#define ResourceUpload_zoom_data_length_tag      5
#define ResourceUpload_file_name_no_ext_tag      6
#define ZoomRequest_offset_tag                   1
#define ZoomRequest_data_length_tag              2
#define ResourceRequest_offset_tag               1
#define ResourceRequest_data_length_tag          2
#define ResourceAck_data_chunk_tag               1
#define ResourceAck_hash_tag                     2
#define ResourceUpdate_file_name_tag             1
#define ResourceUpdate_data_length_tag           2
#define ResourceUpdate_initial_data_chunk_tag    3
#define ResourceUpdate_hash_tag                  4
#define ListResDir_path_tag                      1
#define FileInfoList_files_tag                   1
#define FileInfo_name_tag                        1
#define FileInfo_size_tag                        2
#define UnlockPath_address_n_tag                 1
#define UnlockPath_mac_tag                       2
#define UnlockedPathRequest_mac_tag              1

/* Struct field encoding specification for nanopb */
#define Initialize_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BYTES,    session_id,        1) \
X(a, STATIC,   OPTIONAL, BOOL,     _skip_passphrase,   2) \
X(a, STATIC,   OPTIONAL, BOOL,     derive_cardano,    3)
#define Initialize_CALLBACK NULL
#define Initialize_DEFAULT NULL

#define GetFeatures_FIELDLIST(X, a) \

#define GetFeatures_CALLBACK NULL
#define GetFeatures_DEFAULT NULL

#define Features_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   vendor,            1) \
X(a, STATIC,   REQUIRED, UINT32,   major_version,     2) \
X(a, STATIC,   REQUIRED, UINT32,   minor_version,     3) \
X(a, STATIC,   REQUIRED, UINT32,   patch_version,     4) \
X(a, STATIC,   OPTIONAL, BOOL,     bootloader_mode,   5) \
X(a, STATIC,   OPTIONAL, STRING,   device_id,         6) \
X(a, STATIC,   OPTIONAL, BOOL,     pin_protection,    7) \
X(a, STATIC,   OPTIONAL, BOOL,     passphrase_protection,   8) \
X(a, STATIC,   OPTIONAL, STRING,   language,          9) \
X(a, STATIC,   OPTIONAL, STRING,   label,            10) \
X(a, STATIC,   OPTIONAL, BOOL,     initialized,      12) \
X(a, STATIC,   OPTIONAL, BYTES,    revision,         13) \
X(a, STATIC,   OPTIONAL, BYTES,    bootloader_hash,  14) \
X(a, STATIC,   OPTIONAL, BOOL,     imported,         15) \
X(a, STATIC,   OPTIONAL, BOOL,     unlocked,         16) \
X(a, STATIC,   OPTIONAL, BOOL,     _passphrase_cached,  17) \
X(a, STATIC,   OPTIONAL, BOOL,     firmware_present,  18) \
X(a, STATIC,   OPTIONAL, BOOL,     needs_backup,     19) \
X(a, STATIC,   OPTIONAL, UINT32,   flags,            20) \
X(a, STATIC,   OPTIONAL, STRING,   model,            21) \
X(a, STATIC,   OPTIONAL, UINT32,   fw_major,         22) \
X(a, STATIC,   OPTIONAL, UINT32,   fw_minor,         23) \
X(a, STATIC,   OPTIONAL, UINT32,   fw_patch,         24) \
X(a, STATIC,   OPTIONAL, STRING,   fw_vendor,        25) \
X(a, STATIC,   OPTIONAL, BOOL,     unfinished_backup,  27) \
X(a, STATIC,   OPTIONAL, BOOL,     no_backup,        28) \
X(a, STATIC,   OPTIONAL, BOOL,     recovery_mode,    29) \
X(a, STATIC,   REPEATED, UENUM,    capabilities,     30) \
X(a, STATIC,   OPTIONAL, UENUM,    backup_type,      31) \
X(a, STATIC,   OPTIONAL, BOOL,     sd_card_present,  32) \
X(a, STATIC,   OPTIONAL, BOOL,     sd_protection,    33) \
X(a, STATIC,   OPTIONAL, BOOL,     wipe_code_protection,  34) \
X(a, STATIC,   OPTIONAL, BYTES,    session_id,       35) \
X(a, STATIC,   OPTIONAL, BOOL,     passphrase_always_on_device,  36) \
X(a, STATIC,   OPTIONAL, UENUM,    safety_checks,    37) \
X(a, STATIC,   OPTIONAL, UINT32,   auto_lock_delay_ms,  38) \
X(a, STATIC,   OPTIONAL, UINT32,   display_rotation,  39) \
X(a, STATIC,   OPTIONAL, BOOL,     experimental_features,  40) \
X(a, STATIC,   OPTIONAL, BOOL,     busy,             41) \
X(a, STATIC,   OPTIONAL, UINT32,   offset,          500) \
X(a, STATIC,   OPTIONAL, STRING,   ble_name,        501) \
X(a, STATIC,   OPTIONAL, STRING,   ble_ver,         502) \
X(a, STATIC,   OPTIONAL, BOOL,     ble_enable,      503) \
X(a, STATIC,   OPTIONAL, BOOL,     se_enable,       504) \
X(a, STATIC,   OPTIONAL, STRING,   se_ver,          506) \
X(a, STATIC,   OPTIONAL, BOOL,     backup_only,     507) \
X(a, STATIC,   OPTIONAL, STRING,   hypermate_version, 508) \
X(a, STATIC,   OPTIONAL, STRING,   hypermate_serial, 509) \
X(a, STATIC,   OPTIONAL, STRING,   bootloader_version, 510) \
X(a, STATIC,   OPTIONAL, STRING,   serial_no,       511) \
X(a, STATIC,   OPTIONAL, STRING,   spi_flash,       512) \
X(a, STATIC,   OPTIONAL, UINT32,   initstates,      513) \
X(a, STATIC,   OPTIONAL, BYTES,    NFT_voucher,     514) \
X(a, STATIC,   OPTIONAL, STRING,   cpu_info,        515) \
X(a, STATIC,   OPTIONAL, STRING,   pre_firmware,    516) \
X(a, STATIC,   OPTIONAL, UINT32,   coin_switch,     517) \
X(a, STATIC,   OPTIONAL, BYTES,    build_id,        518) \
X(a, STATIC,   OPTIONAL, STRING,   boardloader_version, 519) \
X(a, STATIC,   OPTIONAL, STRING,   iris_version,    600) \
X(a, STATIC,   OPTIONAL, UINT32,   battery,         601)
#define Features_CALLBACK NULL
#define Features_DEFAULT NULL

#define LockDevice_FIELDLIST(X, a) \

#define LockDevice_CALLBACK NULL
#define LockDevice_DEFAULT NULL

#define SetBusy_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   expiry_ms,         1)
#define SetBusy_CALLBACK NULL
#define SetBusy_DEFAULT NULL

#define EndSession_FIELDLIST(X, a) \

#define EndSession_CALLBACK NULL
#define EndSession_DEFAULT NULL

#define ApplySettings_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   language,          1) \
X(a, CALLBACK, OPTIONAL, STRING,   label,             2) \
X(a, STATIC,   OPTIONAL, BOOL,     use_passphrase,    3) \
X(a, CALLBACK, OPTIONAL, BYTES,    homescreen,        4) \
X(a, STATIC,   OPTIONAL, UINT32,   _passphrase_source,   5) \
X(a, STATIC,   OPTIONAL, UINT32,   auto_lock_delay_ms,   6) \
X(a, STATIC,   OPTIONAL, UINT32,   display_rotation,   7) \
X(a, STATIC,   OPTIONAL, BOOL,     passphrase_always_on_device,   8) \
X(a, STATIC,   OPTIONAL, UENUM,    safety_checks,     9) \
X(a, STATIC,   OPTIONAL, BOOL,     experimental_features,  10)
#define ApplySettings_CALLBACK pb_default_field_callback
#define ApplySettings_DEFAULT NULL

#define ApplyFlags_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   flags,             1)
#define ApplyFlags_CALLBACK NULL
#define ApplyFlags_DEFAULT NULL

#define ChangePin_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     remove,            1)
#define ChangePin_CALLBACK NULL
#define ChangePin_DEFAULT NULL

#define ChangeWipeCode_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     remove,            1)
#define ChangeWipeCode_CALLBACK NULL
#define ChangeWipeCode_DEFAULT NULL

#define SdProtect_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    operation,         1)
#define SdProtect_CALLBACK NULL
#define SdProtect_DEFAULT NULL

#define Ping_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   message,           1) \
X(a, STATIC,   OPTIONAL, BOOL,     button_protection,   2)
#define Ping_CALLBACK NULL
#define Ping_DEFAULT (const pb_byte_t*)"\x0a\x00\x00"

#define Cancel_FIELDLIST(X, a) \

#define Cancel_CALLBACK NULL
#define Cancel_DEFAULT NULL

#define GetEntropy_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   size,              1)
#define GetEntropy_CALLBACK NULL
#define GetEntropy_DEFAULT NULL

#define Entropy_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, BYTES,    entropy,           1)
#define Entropy_CALLBACK pb_default_field_callback
#define Entropy_DEFAULT NULL

#define GetFirmwareHash_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, BYTES,    challenge,         1)
#define GetFirmwareHash_CALLBACK pb_default_field_callback
#define GetFirmwareHash_DEFAULT NULL

#define FirmwareHash_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, BYTES,    hash,              1)
#define FirmwareHash_CALLBACK pb_default_field_callback
#define FirmwareHash_DEFAULT NULL

#define WipeDevice_FIELDLIST(X, a) \

#define WipeDevice_CALLBACK NULL
#define WipeDevice_DEFAULT NULL

#define LoadDevice_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   mnemonics,         1) \
X(a, CALLBACK, OPTIONAL, STRING,   pin,               3) \
X(a, STATIC,   OPTIONAL, BOOL,     passphrase_protection,   4) \
X(a, CALLBACK, OPTIONAL, STRING,   language,          5) \
X(a, CALLBACK, OPTIONAL, STRING,   label,             6) \
X(a, STATIC,   OPTIONAL, BOOL,     skip_checksum,     7) \
X(a, STATIC,   OPTIONAL, UINT32,   u2f_counter,       8) \
X(a, STATIC,   OPTIONAL, BOOL,     needs_backup,      9) \
X(a, STATIC,   OPTIONAL, BOOL,     no_backup,        10)
#define LoadDevice_CALLBACK pb_default_field_callback
#define LoadDevice_DEFAULT NULL

#define ResetDevice_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     display_random,    1) \
X(a, STATIC,   OPTIONAL, UINT32,   strength,          2) \
X(a, STATIC,   OPTIONAL, BOOL,     passphrase_protection,   3) \
X(a, STATIC,   OPTIONAL, BOOL,     pin_protection,    4) \
X(a, CALLBACK, OPTIONAL, STRING,   language,          5) \
X(a, CALLBACK, OPTIONAL, STRING,   label,             6) \
X(a, STATIC,   OPTIONAL, UINT32,   u2f_counter,       7) \
X(a, STATIC,   OPTIONAL, BOOL,     skip_backup,       8) \
X(a, STATIC,   OPTIONAL, BOOL,     no_backup,         9) \
X(a, STATIC,   OPTIONAL, UENUM,    backup_type,      10)
#define ResetDevice_CALLBACK pb_default_field_callback
#define ResetDevice_DEFAULT (const pb_byte_t*)"\x10\x80\x02\x00"

#define BackupDevice_FIELDLIST(X, a) \

#define BackupDevice_CALLBACK NULL
#define BackupDevice_DEFAULT NULL

#define EntropyRequest_FIELDLIST(X, a) \

#define EntropyRequest_CALLBACK NULL
#define EntropyRequest_DEFAULT NULL

#define EntropyAck_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, BYTES,    entropy,           1)
#define EntropyAck_CALLBACK pb_default_field_callback
#define EntropyAck_DEFAULT NULL

#define RecoveryDevice_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   word_count,        1) \
X(a, STATIC,   OPTIONAL, BOOL,     passphrase_protection,   2) \
X(a, STATIC,   OPTIONAL, BOOL,     pin_protection,    3) \
X(a, CALLBACK, OPTIONAL, STRING,   language,          4) \
X(a, CALLBACK, OPTIONAL, STRING,   label,             5) \
X(a, STATIC,   OPTIONAL, BOOL,     enforce_wordlist,   6) \
X(a, STATIC,   OPTIONAL, UENUM,    type,              8) \
X(a, STATIC,   OPTIONAL, UINT32,   u2f_counter,       9) \
X(a, STATIC,   OPTIONAL, BOOL,     dry_run,          10)
#define RecoveryDevice_CALLBACK pb_default_field_callback
#define RecoveryDevice_DEFAULT NULL

#define WordRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    type,              1)
#define WordRequest_CALLBACK NULL
#define WordRequest_DEFAULT NULL

#define WordAck_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   word,              1)
#define WordAck_CALLBACK pb_default_field_callback
#define WordAck_DEFAULT NULL

#define SetU2FCounter_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   u2f_counter,       1)
#define SetU2FCounter_CALLBACK NULL
#define SetU2FCounter_DEFAULT NULL

#define GetNextU2FCounter_FIELDLIST(X, a) \

#define GetNextU2FCounter_CALLBACK NULL
#define GetNextU2FCounter_DEFAULT NULL

#define NextU2FCounter_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   u2f_counter,       1)
#define NextU2FCounter_CALLBACK NULL
#define NextU2FCounter_DEFAULT NULL

#define DoPreauthorized_FIELDLIST(X, a) \

#define DoPreauthorized_CALLBACK NULL
#define DoPreauthorized_DEFAULT NULL

#define PreauthorizedRequest_FIELDLIST(X, a) \

#define PreauthorizedRequest_CALLBACK NULL
#define PreauthorizedRequest_DEFAULT NULL

#define CancelAuthorization_FIELDLIST(X, a) \

#define CancelAuthorization_CALLBACK NULL
#define CancelAuthorization_DEFAULT NULL

#define RebootToBootloader_FIELDLIST(X, a) \

#define RebootToBootloader_CALLBACK NULL
#define RebootToBootloader_DEFAULT NULL

#define RebootToBoardloader_FIELDLIST(X, a) \

#define RebootToBoardloader_CALLBACK NULL
#define RebootToBoardloader_DEFAULT NULL

#define GetNonce_FIELDLIST(X, a) \

#define GetNonce_CALLBACK NULL
#define GetNonce_DEFAULT NULL

#define Nonce_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, BYTES,    nonce,             1)
#define Nonce_CALLBACK pb_default_field_callback
#define Nonce_DEFAULT NULL

#define DeviceBackToBoot_FIELDLIST(X, a) \

#define DeviceBackToBoot_CALLBACK NULL
#define DeviceBackToBoot_DEFAULT NULL

#define DeviceInfoSettings_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   serial_no,         1) \
X(a, STATIC,   OPTIONAL, STRING,   cpu_info,          2) \
X(a, STATIC,   OPTIONAL, STRING,   pre_firmware,      3)
#define DeviceInfoSettings_CALLBACK NULL
#define DeviceInfoSettings_DEFAULT NULL

#define GetDeviceInfo_FIELDLIST(X, a) \

#define GetDeviceInfo_CALLBACK NULL
#define GetDeviceInfo_DEFAULT NULL

#define DeviceInfo_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   serial_no,         1) \
X(a, CALLBACK, OPTIONAL, STRING,   spiFlash_info,     2) \
X(a, CALLBACK, OPTIONAL, STRING,   SE_info,           3) \
X(a, CALLBACK, OPTIONAL, BYTES,    NFT_voucher,       4) \
X(a, CALLBACK, OPTIONAL, STRING,   cpu_info,          5) \
X(a, CALLBACK, OPTIONAL, STRING,   pre_firmware,      6)
#define DeviceInfo_CALLBACK pb_default_field_callback
#define DeviceInfo_DEFAULT NULL

#define ReadSEPublicKey_FIELDLIST(X, a) \

#define ReadSEPublicKey_CALLBACK NULL
#define ReadSEPublicKey_DEFAULT NULL

#define SEPublicKey_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BYTES,    public_key,        1)
#define SEPublicKey_CALLBACK NULL
#define SEPublicKey_DEFAULT NULL

#define WriteSEPublicCert_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BYTES,    public_cert,       1)
#define WriteSEPublicCert_CALLBACK NULL
#define WriteSEPublicCert_DEFAULT NULL

#define ReadSEPublicCert_FIELDLIST(X, a) \

#define ReadSEPublicCert_CALLBACK NULL
#define ReadSEPublicCert_DEFAULT NULL

#define SEPublicCert_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BYTES,    public_cert,       1)
#define SEPublicCert_CALLBACK NULL
#define SEPublicCert_DEFAULT NULL

#define SESignMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BYTES,    message,           1)
#define SESignMessage_CALLBACK NULL
#define SESignMessage_DEFAULT NULL

#define SEMessageSignature_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BYTES,    signature,         1)
#define SEMessageSignature_CALLBACK NULL
#define SEMessageSignature_DEFAULT NULL

#define SEInitialize_FIELDLIST(X, a) \

#define SEInitialize_CALLBACK NULL
#define SEInitialize_DEFAULT NULL

#define SEInitializeDone_FIELDLIST(X, a) \

#define SEInitializeDone_CALLBACK NULL
#define SEInitializeDone_DEFAULT NULL

#define SEBackToRomBoot_FIELDLIST(X, a) \

#define SEBackToRomBoot_CALLBACK NULL
#define SEBackToRomBoot_DEFAULT NULL

#define SEWipeUserStorage_FIELDLIST(X, a) \

#define SEWipeUserStorage_CALLBACK NULL
#define SEWipeUserStorage_DEFAULT NULL

#define ResourceUpload_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   extension,         1) \
X(a, STATIC,   REQUIRED, UINT32,   data_length,       2) \
X(a, STATIC,   REQUIRED, UENUM,    res_type,          3) \
X(a, CALLBACK, OPTIONAL, BYTES,    nft_meta_data,     4) \
X(a, STATIC,   REQUIRED, UINT32,   zoom_data_length,   5) \
X(a, CALLBACK, OPTIONAL, STRING,   file_name_no_ext,   6)
#define ResourceUpload_CALLBACK pb_default_field_callback
#define ResourceUpload_DEFAULT NULL

#define ZoomRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   offset,            1) \
X(a, STATIC,   REQUIRED, UINT32,   data_length,       2)
#define ZoomRequest_CALLBACK NULL
#define ZoomRequest_DEFAULT NULL

#define ResourceRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   offset,            1) \
X(a, STATIC,   REQUIRED, UINT32,   data_length,       2)
#define ResourceRequest_CALLBACK NULL
#define ResourceRequest_DEFAULT NULL

#define ResourceAck_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, BYTES,    data_chunk,        1) \
X(a, CALLBACK, OPTIONAL, BYTES,    hash,              2)
#define ResourceAck_CALLBACK pb_default_field_callback
#define ResourceAck_DEFAULT NULL

#define ResourceUpdate_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   file_name,         1) \
X(a, STATIC,   REQUIRED, UINT32,   data_length,       2) \
X(a, CALLBACK, REQUIRED, BYTES,    initial_data_chunk,   3) \
X(a, CALLBACK, OPTIONAL, BYTES,    hash,              4)
#define ResourceUpdate_CALLBACK pb_default_field_callback
#define ResourceUpdate_DEFAULT NULL

#define ListResDir_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   path,              1)
#define ListResDir_CALLBACK pb_default_field_callback
#define ListResDir_DEFAULT NULL

#define FileInfoList_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  files,             1)
#define FileInfoList_CALLBACK pb_default_field_callback
#define FileInfoList_DEFAULT NULL
#define FileInfoList_files_MSGTYPE FileInfo

#define FileInfo_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   name,              1) \
X(a, STATIC,   REQUIRED, UINT64,   size,              2)
#define FileInfo_CALLBACK pb_default_field_callback
#define FileInfo_DEFAULT NULL

#define UnlockPath_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UINT32,   address_n,         1) \
X(a, CALLBACK, OPTIONAL, BYTES,    mac,               2)
#define UnlockPath_CALLBACK pb_default_field_callback
#define UnlockPath_DEFAULT NULL

#define UnlockedPathRequest_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, BYTES,    mac,               1)
#define UnlockedPathRequest_CALLBACK pb_default_field_callback
#define UnlockedPathRequest_DEFAULT NULL

extern const pb_msgdesc_t Initialize_msg;
extern const pb_msgdesc_t GetFeatures_msg;
extern const pb_msgdesc_t Features_msg;
extern const pb_msgdesc_t LockDevice_msg;
extern const pb_msgdesc_t SetBusy_msg;
extern const pb_msgdesc_t EndSession_msg;
extern const pb_msgdesc_t ApplySettings_msg;
extern const pb_msgdesc_t ApplyFlags_msg;
extern const pb_msgdesc_t ChangePin_msg;
extern const pb_msgdesc_t ChangeWipeCode_msg;
extern const pb_msgdesc_t SdProtect_msg;
extern const pb_msgdesc_t Ping_msg;
extern const pb_msgdesc_t Cancel_msg;
extern const pb_msgdesc_t GetEntropy_msg;
extern const pb_msgdesc_t Entropy_msg;
extern const pb_msgdesc_t GetFirmwareHash_msg;
extern const pb_msgdesc_t FirmwareHash_msg;
extern const pb_msgdesc_t WipeDevice_msg;
extern const pb_msgdesc_t LoadDevice_msg;
extern const pb_msgdesc_t ResetDevice_msg;
extern const pb_msgdesc_t BackupDevice_msg;
extern const pb_msgdesc_t EntropyRequest_msg;
extern const pb_msgdesc_t EntropyAck_msg;
extern const pb_msgdesc_t RecoveryDevice_msg;
extern const pb_msgdesc_t WordRequest_msg;
extern const pb_msgdesc_t WordAck_msg;
extern const pb_msgdesc_t SetU2FCounter_msg;
extern const pb_msgdesc_t GetNextU2FCounter_msg;
extern const pb_msgdesc_t NextU2FCounter_msg;
extern const pb_msgdesc_t DoPreauthorized_msg;
extern const pb_msgdesc_t PreauthorizedRequest_msg;
extern const pb_msgdesc_t CancelAuthorization_msg;
extern const pb_msgdesc_t RebootToBootloader_msg;
extern const pb_msgdesc_t RebootToBoardloader_msg;
extern const pb_msgdesc_t GetNonce_msg;
extern const pb_msgdesc_t Nonce_msg;
extern const pb_msgdesc_t DeviceBackToBoot_msg;
extern const pb_msgdesc_t DeviceInfoSettings_msg;
extern const pb_msgdesc_t GetDeviceInfo_msg;
extern const pb_msgdesc_t DeviceInfo_msg;
extern const pb_msgdesc_t ReadSEPublicKey_msg;
extern const pb_msgdesc_t SEPublicKey_msg;
extern const pb_msgdesc_t WriteSEPublicCert_msg;
extern const pb_msgdesc_t ReadSEPublicCert_msg;
extern const pb_msgdesc_t SEPublicCert_msg;
extern const pb_msgdesc_t SESignMessage_msg;
extern const pb_msgdesc_t SEMessageSignature_msg;
extern const pb_msgdesc_t SEInitialize_msg;
extern const pb_msgdesc_t SEInitializeDone_msg;
extern const pb_msgdesc_t SEBackToRomBoot_msg;
extern const pb_msgdesc_t SEWipeUserStorage_msg;
extern const pb_msgdesc_t ResourceUpload_msg;
extern const pb_msgdesc_t ZoomRequest_msg;
extern const pb_msgdesc_t ResourceRequest_msg;
extern const pb_msgdesc_t ResourceAck_msg;
extern const pb_msgdesc_t ResourceUpdate_msg;
extern const pb_msgdesc_t ListResDir_msg;
extern const pb_msgdesc_t FileInfoList_msg;
extern const pb_msgdesc_t FileInfo_msg;
extern const pb_msgdesc_t UnlockPath_msg;
extern const pb_msgdesc_t UnlockedPathRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Initialize_fields &Initialize_msg
#define GetFeatures_fields &GetFeatures_msg
#define Features_fields &Features_msg
#define LockDevice_fields &LockDevice_msg
#define SetBusy_fields &SetBusy_msg
#define EndSession_fields &EndSession_msg
#define ApplySettings_fields &ApplySettings_msg
#define ApplyFlags_fields &ApplyFlags_msg
#define ChangePin_fields &ChangePin_msg
#define ChangeWipeCode_fields &ChangeWipeCode_msg
#define SdProtect_fields &SdProtect_msg
#define Ping_fields &Ping_msg
#define Cancel_fields &Cancel_msg
#define GetEntropy_fields &GetEntropy_msg
#define Entropy_fields &Entropy_msg
#define GetFirmwareHash_fields &GetFirmwareHash_msg
#define FirmwareHash_fields &FirmwareHash_msg
#define WipeDevice_fields &WipeDevice_msg
#define LoadDevice_fields &LoadDevice_msg
#define ResetDevice_fields &ResetDevice_msg
#define BackupDevice_fields &BackupDevice_msg
#define EntropyRequest_fields &EntropyRequest_msg
#define EntropyAck_fields &EntropyAck_msg
#define RecoveryDevice_fields &RecoveryDevice_msg
#define WordRequest_fields &WordRequest_msg
#define WordAck_fields &WordAck_msg
#define SetU2FCounter_fields &SetU2FCounter_msg
#define GetNextU2FCounter_fields &GetNextU2FCounter_msg
#define NextU2FCounter_fields &NextU2FCounter_msg
#define DoPreauthorized_fields &DoPreauthorized_msg
#define PreauthorizedRequest_fields &PreauthorizedRequest_msg
#define CancelAuthorization_fields &CancelAuthorization_msg
#define RebootToBootloader_fields &RebootToBootloader_msg
#define RebootToBoardloader_fields &RebootToBoardloader_msg
#define GetNonce_fields &GetNonce_msg
#define Nonce_fields &Nonce_msg
#define DeviceBackToBoot_fields &DeviceBackToBoot_msg
#define DeviceInfoSettings_fields &DeviceInfoSettings_msg
#define GetDeviceInfo_fields &GetDeviceInfo_msg
#define DeviceInfo_fields &DeviceInfo_msg
#define ReadSEPublicKey_fields &ReadSEPublicKey_msg
#define SEPublicKey_fields &SEPublicKey_msg
#define WriteSEPublicCert_fields &WriteSEPublicCert_msg
#define ReadSEPublicCert_fields &ReadSEPublicCert_msg
#define SEPublicCert_fields &SEPublicCert_msg
#define SESignMessage_fields &SESignMessage_msg
#define SEMessageSignature_fields &SEMessageSignature_msg
#define SEInitialize_fields &SEInitialize_msg
#define SEInitializeDone_fields &SEInitializeDone_msg
#define SEBackToRomBoot_fields &SEBackToRomBoot_msg
#define SEWipeUserStorage_fields &SEWipeUserStorage_msg
#define ResourceUpload_fields &ResourceUpload_msg
#define ZoomRequest_fields &ZoomRequest_msg
#define ResourceRequest_fields &ResourceRequest_msg
#define ResourceAck_fields &ResourceAck_msg
#define ResourceUpdate_fields &ResourceUpdate_msg
#define ListResDir_fields &ListResDir_msg
#define FileInfoList_fields &FileInfoList_msg
#define FileInfo_fields &FileInfo_msg
#define UnlockPath_fields &UnlockPath_msg
#define UnlockedPathRequest_fields &UnlockedPathRequest_msg

/* Maximum encoded size of messages (where known) */
/* ApplySettings_size depends on runtime parameters */
/* Entropy_size depends on runtime parameters */
/* GetFirmwareHash_size depends on runtime parameters */
/* FirmwareHash_size depends on runtime parameters */
/* LoadDevice_size depends on runtime parameters */
/* ResetDevice_size depends on runtime parameters */
/* EntropyAck_size depends on runtime parameters */
/* RecoveryDevice_size depends on runtime parameters */
/* WordAck_size depends on runtime parameters */
/* Nonce_size depends on runtime parameters */
/* DeviceInfo_size depends on runtime parameters */
/* ResourceUpload_size depends on runtime parameters */
/* ResourceAck_size depends on runtime parameters */
/* ResourceUpdate_size depends on runtime parameters */
/* ListResDir_size depends on runtime parameters */
/* FileInfoList_size depends on runtime parameters */
/* FileInfo_size depends on runtime parameters */
/* UnlockPath_size depends on runtime parameters */
/* UnlockedPathRequest_size depends on runtime parameters */
#define ApplyFlags_size                          6
#define BackupDevice_size                        0
#define CancelAuthorization_size                 0
#define Cancel_size                              0
#define ChangePin_size                           2
#define ChangeWipeCode_size                      2
#define DeviceBackToBoot_size                    0
#define DeviceInfoSettings_size                  67
#define DoPreauthorized_size                     0
#define EndSession_size                          0
#define EntropyRequest_size                      0
#define Features_size                            1095
#define GetDeviceInfo_size                       0
#define GetEntropy_size                          6
#define GetFeatures_size                         0
#define GetNextU2FCounter_size                   0
#define GetNonce_size                            0
#define HW_TREZOR_MESSAGES_MANAGEMENT_MESSAGES_MANAGEMENT_PB_H_MAX_SIZE Features_size
#define Initialize_size                          38
#define LockDevice_size                          0
#define NextU2FCounter_size                      6
#define Ping_size                                260
#define PreauthorizedRequest_size                0
#define ReadSEPublicCert_size                    0
#define ReadSEPublicKey_size                     0
#define RebootToBoardloader_size                 0
#define RebootToBootloader_size                  0
#define ResourceRequest_size                     12
#define SEBackToRomBoot_size                     0
#define SEInitializeDone_size                    0
#define SEInitialize_size                        0
#define SEMessageSignature_size                  66
#define SEPublicCert_size                        1027
#define SEPublicKey_size                         67
#define SESignMessage_size                       515
#define SEWipeUserStorage_size                   0
#define SdProtect_size                           2
#define SetBusy_size                             6
#define SetU2FCounter_size                       6
#define WipeDevice_size                          0
#define WordRequest_size                         2
#define WriteSEPublicCert_size                   1027
#define ZoomRequest_size                         12

/* Mapping from canonical names (mangle_names or overridden package name) */
#define hw_trezor_messages_management_BackupType BackupType
#define hw_trezor_messages_management_SafetyCheckLevel SafetyCheckLevel
#define hw_trezor_messages_management_Initialize Initialize
#define hw_trezor_messages_management_GetFeatures GetFeatures
#define hw_trezor_messages_management_Features Features
#define hw_trezor_messages_management_Features_Capability Capability
#define hw_trezor_messages_management_LockDevice LockDevice
#define hw_trezor_messages_management_SetBusy SetBusy
#define hw_trezor_messages_management_EndSession EndSession
#define hw_trezor_messages_management_ApplySettings ApplySettings
#define hw_trezor_messages_management_ApplyFlags ApplyFlags
#define hw_trezor_messages_management_ChangePin ChangePin
#define hw_trezor_messages_management_ChangeWipeCode ChangeWipeCode
#define hw_trezor_messages_management_SdProtect SdProtect
#define hw_trezor_messages_management_SdProtect_SdProtectOperationType SdProtectOperationType
#define hw_trezor_messages_management_Ping Ping
#define hw_trezor_messages_management_Cancel Cancel
#define hw_trezor_messages_management_GetEntropy GetEntropy
#define hw_trezor_messages_management_Entropy Entropy
#define hw_trezor_messages_management_GetFirmwareHash GetFirmwareHash
#define hw_trezor_messages_management_FirmwareHash FirmwareHash
#define hw_trezor_messages_management_WipeDevice WipeDevice
#define hw_trezor_messages_management_LoadDevice LoadDevice
#define hw_trezor_messages_management_ResetDevice ResetDevice
#define hw_trezor_messages_management_BackupDevice BackupDevice
#define hw_trezor_messages_management_EntropyRequest EntropyRequest
#define hw_trezor_messages_management_EntropyAck EntropyAck
#define hw_trezor_messages_management_RecoveryDevice RecoveryDevice
#define hw_trezor_messages_management_RecoveryDevice_RecoveryDeviceType RecoveryDeviceType
#define hw_trezor_messages_management_WordRequest WordRequest
#define hw_trezor_messages_management_WordRequest_WordRequestType WordRequestType
#define hw_trezor_messages_management_WordAck WordAck
#define hw_trezor_messages_management_SetU2FCounter SetU2FCounter
#define hw_trezor_messages_management_GetNextU2FCounter GetNextU2FCounter
#define hw_trezor_messages_management_NextU2FCounter NextU2FCounter
#define hw_trezor_messages_management_DoPreauthorized DoPreauthorized
#define hw_trezor_messages_management_PreauthorizedRequest PreauthorizedRequest
#define hw_trezor_messages_management_CancelAuthorization CancelAuthorization
#define hw_trezor_messages_management_RebootToBootloader RebootToBootloader
#define hw_trezor_messages_management_RebootToBoardloader RebootToBoardloader
#define hw_trezor_messages_management_GetNonce GetNonce
#define hw_trezor_messages_management_Nonce Nonce
#define hw_trezor_messages_management_DeviceBackToBoot DeviceBackToBoot
#define hw_trezor_messages_management_DeviceInfoSettings DeviceInfoSettings
#define hw_trezor_messages_management_GetDeviceInfo GetDeviceInfo
#define hw_trezor_messages_management_DeviceInfo DeviceInfo
#define hw_trezor_messages_management_ReadSEPublicKey ReadSEPublicKey
#define hw_trezor_messages_management_SEPublicKey SEPublicKey
#define hw_trezor_messages_management_WriteSEPublicCert WriteSEPublicCert
#define hw_trezor_messages_management_ReadSEPublicCert ReadSEPublicCert
#define hw_trezor_messages_management_SEPublicCert SEPublicCert
#define hw_trezor_messages_management_SESignMessage SESignMessage
#define hw_trezor_messages_management_SEMessageSignature SEMessageSignature
#define hw_trezor_messages_management_SEInitialize SEInitialize
#define hw_trezor_messages_management_SEInitializeDone SEInitializeDone
#define hw_trezor_messages_management_SEBackToRomBoot SEBackToRomBoot
#define hw_trezor_messages_management_SEWipeUserStorage SEWipeUserStorage
#define hw_trezor_messages_management_ResourceUpload ResourceUpload
#define hw_trezor_messages_management_ResourceUpload_ResourceType ResourceType
#define hw_trezor_messages_management_ZoomRequest ZoomRequest
#define hw_trezor_messages_management_ResourceRequest ResourceRequest
#define hw_trezor_messages_management_ResourceAck ResourceAck
#define hw_trezor_messages_management_ResourceUpdate ResourceUpdate
#define hw_trezor_messages_management_ListResDir ListResDir
#define hw_trezor_messages_management_FileInfoList FileInfoList
#define hw_trezor_messages_management_FileInfo FileInfo
#define hw_trezor_messages_management_UnlockPath UnlockPath
#define hw_trezor_messages_management_UnlockedPathRequest UnlockedPathRequest
#define _hw_trezor_messages_management_BackupType_MIN _BackupType_MIN
#define _hw_trezor_messages_management_BackupType_MAX _BackupType_MAX
#define _hw_trezor_messages_management_BackupType_ARRAYSIZE _BackupType_ARRAYSIZE
#define _hw_trezor_messages_management_SafetyCheckLevel_MIN _SafetyCheckLevel_MIN
#define _hw_trezor_messages_management_SafetyCheckLevel_MAX _SafetyCheckLevel_MAX
#define _hw_trezor_messages_management_SafetyCheckLevel_ARRAYSIZE _SafetyCheckLevel_ARRAYSIZE
#define _hw_trezor_messages_management_Features_Capability_MIN _Capability_MIN
#define _hw_trezor_messages_management_Features_Capability_MAX _Capability_MAX
#define _hw_trezor_messages_management_Features_Capability_ARRAYSIZE _Capability_ARRAYSIZE
#define _hw_trezor_messages_management_SdProtect_SdProtectOperationType_MIN _SdProtectOperationType_MIN
#define _hw_trezor_messages_management_SdProtect_SdProtectOperationType_MAX _SdProtectOperationType_MAX
#define _hw_trezor_messages_management_SdProtect_SdProtectOperationType_ARRAYSIZE _SdProtectOperationType_ARRAYSIZE
#define _hw_trezor_messages_management_RecoveryDevice_RecoveryDeviceType_MIN _RecoveryDeviceType_MIN
#define _hw_trezor_messages_management_RecoveryDevice_RecoveryDeviceType_MAX _RecoveryDeviceType_MAX
#define _hw_trezor_messages_management_RecoveryDevice_RecoveryDeviceType_ARRAYSIZE _RecoveryDeviceType_ARRAYSIZE
#define _hw_trezor_messages_management_WordRequest_WordRequestType_MIN _WordRequestType_MIN
#define _hw_trezor_messages_management_WordRequest_WordRequestType_MAX _WordRequestType_MAX
#define _hw_trezor_messages_management_WordRequest_WordRequestType_ARRAYSIZE _WordRequestType_ARRAYSIZE
#define _hw_trezor_messages_management_ResourceUpload_ResourceType_MIN _ResourceType_MIN
#define _hw_trezor_messages_management_ResourceUpload_ResourceType_MAX _ResourceType_MAX
#define _hw_trezor_messages_management_ResourceUpload_ResourceType_ARRAYSIZE _ResourceType_ARRAYSIZE
#define hw_trezor_messages_management_Initialize_init_default Initialize_init_default
#define hw_trezor_messages_management_GetFeatures_init_default GetFeatures_init_default
#define hw_trezor_messages_management_Features_init_default Features_init_default
#define hw_trezor_messages_management_LockDevice_init_default LockDevice_init_default
#define hw_trezor_messages_management_SetBusy_init_default SetBusy_init_default
#define hw_trezor_messages_management_EndSession_init_default EndSession_init_default
#define hw_trezor_messages_management_ApplySettings_init_default ApplySettings_init_default
#define hw_trezor_messages_management_ApplyFlags_init_default ApplyFlags_init_default
#define hw_trezor_messages_management_ChangePin_init_default ChangePin_init_default
#define hw_trezor_messages_management_ChangeWipeCode_init_default ChangeWipeCode_init_default
#define hw_trezor_messages_management_SdProtect_init_default SdProtect_init_default
#define hw_trezor_messages_management_Ping_init_default Ping_init_default
#define hw_trezor_messages_management_Cancel_init_default Cancel_init_default
#define hw_trezor_messages_management_GetEntropy_init_default GetEntropy_init_default
#define hw_trezor_messages_management_Entropy_init_default Entropy_init_default
#define hw_trezor_messages_management_GetFirmwareHash_init_default GetFirmwareHash_init_default
#define hw_trezor_messages_management_FirmwareHash_init_default FirmwareHash_init_default
#define hw_trezor_messages_management_WipeDevice_init_default WipeDevice_init_default
#define hw_trezor_messages_management_LoadDevice_init_default LoadDevice_init_default
#define hw_trezor_messages_management_ResetDevice_init_default ResetDevice_init_default
#define hw_trezor_messages_management_BackupDevice_init_default BackupDevice_init_default
#define hw_trezor_messages_management_EntropyRequest_init_default EntropyRequest_init_default
#define hw_trezor_messages_management_EntropyAck_init_default EntropyAck_init_default
#define hw_trezor_messages_management_RecoveryDevice_init_default RecoveryDevice_init_default
#define hw_trezor_messages_management_WordRequest_init_default WordRequest_init_default
#define hw_trezor_messages_management_WordAck_init_default WordAck_init_default
#define hw_trezor_messages_management_SetU2FCounter_init_default SetU2FCounter_init_default
#define hw_trezor_messages_management_GetNextU2FCounter_init_default GetNextU2FCounter_init_default
#define hw_trezor_messages_management_NextU2FCounter_init_default NextU2FCounter_init_default
#define hw_trezor_messages_management_DoPreauthorized_init_default DoPreauthorized_init_default
#define hw_trezor_messages_management_PreauthorizedRequest_init_default PreauthorizedRequest_init_default
#define hw_trezor_messages_management_CancelAuthorization_init_default CancelAuthorization_init_default
#define hw_trezor_messages_management_RebootToBootloader_init_default RebootToBootloader_init_default
#define hw_trezor_messages_management_RebootToBoardloader_init_default RebootToBoardloader_init_default
#define hw_trezor_messages_management_GetNonce_init_default GetNonce_init_default
#define hw_trezor_messages_management_Nonce_init_default Nonce_init_default
#define hw_trezor_messages_management_DeviceBackToBoot_init_default DeviceBackToBoot_init_default
#define hw_trezor_messages_management_DeviceInfoSettings_init_default DeviceInfoSettings_init_default
#define hw_trezor_messages_management_GetDeviceInfo_init_default GetDeviceInfo_init_default
#define hw_trezor_messages_management_DeviceInfo_init_default DeviceInfo_init_default
#define hw_trezor_messages_management_ReadSEPublicKey_init_default ReadSEPublicKey_init_default
#define hw_trezor_messages_management_SEPublicKey_init_default SEPublicKey_init_default
#define hw_trezor_messages_management_WriteSEPublicCert_init_default WriteSEPublicCert_init_default
#define hw_trezor_messages_management_ReadSEPublicCert_init_default ReadSEPublicCert_init_default
#define hw_trezor_messages_management_SEPublicCert_init_default SEPublicCert_init_default
#define hw_trezor_messages_management_SESignMessage_init_default SESignMessage_init_default
#define hw_trezor_messages_management_SEMessageSignature_init_default SEMessageSignature_init_default
#define hw_trezor_messages_management_SEInitialize_init_default SEInitialize_init_default
#define hw_trezor_messages_management_SEInitializeDone_init_default SEInitializeDone_init_default
#define hw_trezor_messages_management_SEBackToRomBoot_init_default SEBackToRomBoot_init_default
#define hw_trezor_messages_management_SEWipeUserStorage_init_default SEWipeUserStorage_init_default
#define hw_trezor_messages_management_ResourceUpload_init_default ResourceUpload_init_default
#define hw_trezor_messages_management_ZoomRequest_init_default ZoomRequest_init_default
#define hw_trezor_messages_management_ResourceRequest_init_default ResourceRequest_init_default
#define hw_trezor_messages_management_ResourceAck_init_default ResourceAck_init_default
#define hw_trezor_messages_management_ResourceUpdate_init_default ResourceUpdate_init_default
#define hw_trezor_messages_management_ListResDir_init_default ListResDir_init_default
#define hw_trezor_messages_management_FileInfoList_init_default FileInfoList_init_default
#define hw_trezor_messages_management_FileInfo_init_default FileInfo_init_default
#define hw_trezor_messages_management_UnlockPath_init_default UnlockPath_init_default
#define hw_trezor_messages_management_UnlockedPathRequest_init_default UnlockedPathRequest_init_default
#define hw_trezor_messages_management_Initialize_init_zero Initialize_init_zero
#define hw_trezor_messages_management_GetFeatures_init_zero GetFeatures_init_zero
#define hw_trezor_messages_management_Features_init_zero Features_init_zero
#define hw_trezor_messages_management_LockDevice_init_zero LockDevice_init_zero
#define hw_trezor_messages_management_SetBusy_init_zero SetBusy_init_zero
#define hw_trezor_messages_management_EndSession_init_zero EndSession_init_zero
#define hw_trezor_messages_management_ApplySettings_init_zero ApplySettings_init_zero
#define hw_trezor_messages_management_ApplyFlags_init_zero ApplyFlags_init_zero
#define hw_trezor_messages_management_ChangePin_init_zero ChangePin_init_zero
#define hw_trezor_messages_management_ChangeWipeCode_init_zero ChangeWipeCode_init_zero
#define hw_trezor_messages_management_SdProtect_init_zero SdProtect_init_zero
#define hw_trezor_messages_management_Ping_init_zero Ping_init_zero
#define hw_trezor_messages_management_Cancel_init_zero Cancel_init_zero
#define hw_trezor_messages_management_GetEntropy_init_zero GetEntropy_init_zero
#define hw_trezor_messages_management_Entropy_init_zero Entropy_init_zero
#define hw_trezor_messages_management_GetFirmwareHash_init_zero GetFirmwareHash_init_zero
#define hw_trezor_messages_management_FirmwareHash_init_zero FirmwareHash_init_zero
#define hw_trezor_messages_management_WipeDevice_init_zero WipeDevice_init_zero
#define hw_trezor_messages_management_LoadDevice_init_zero LoadDevice_init_zero
#define hw_trezor_messages_management_ResetDevice_init_zero ResetDevice_init_zero
#define hw_trezor_messages_management_BackupDevice_init_zero BackupDevice_init_zero
#define hw_trezor_messages_management_EntropyRequest_init_zero EntropyRequest_init_zero
#define hw_trezor_messages_management_EntropyAck_init_zero EntropyAck_init_zero
#define hw_trezor_messages_management_RecoveryDevice_init_zero RecoveryDevice_init_zero
#define hw_trezor_messages_management_WordRequest_init_zero WordRequest_init_zero
#define hw_trezor_messages_management_WordAck_init_zero WordAck_init_zero
#define hw_trezor_messages_management_SetU2FCounter_init_zero SetU2FCounter_init_zero
#define hw_trezor_messages_management_GetNextU2FCounter_init_zero GetNextU2FCounter_init_zero
#define hw_trezor_messages_management_NextU2FCounter_init_zero NextU2FCounter_init_zero
#define hw_trezor_messages_management_DoPreauthorized_init_zero DoPreauthorized_init_zero
#define hw_trezor_messages_management_PreauthorizedRequest_init_zero PreauthorizedRequest_init_zero
#define hw_trezor_messages_management_CancelAuthorization_init_zero CancelAuthorization_init_zero
#define hw_trezor_messages_management_RebootToBootloader_init_zero RebootToBootloader_init_zero
#define hw_trezor_messages_management_RebootToBoardloader_init_zero RebootToBoardloader_init_zero
#define hw_trezor_messages_management_GetNonce_init_zero GetNonce_init_zero
#define hw_trezor_messages_management_Nonce_init_zero Nonce_init_zero
#define hw_trezor_messages_management_DeviceBackToBoot_init_zero DeviceBackToBoot_init_zero
#define hw_trezor_messages_management_DeviceInfoSettings_init_zero DeviceInfoSettings_init_zero
#define hw_trezor_messages_management_GetDeviceInfo_init_zero GetDeviceInfo_init_zero
#define hw_trezor_messages_management_DeviceInfo_init_zero DeviceInfo_init_zero
#define hw_trezor_messages_management_ReadSEPublicKey_init_zero ReadSEPublicKey_init_zero
#define hw_trezor_messages_management_SEPublicKey_init_zero SEPublicKey_init_zero
#define hw_trezor_messages_management_WriteSEPublicCert_init_zero WriteSEPublicCert_init_zero
#define hw_trezor_messages_management_ReadSEPublicCert_init_zero ReadSEPublicCert_init_zero
#define hw_trezor_messages_management_SEPublicCert_init_zero SEPublicCert_init_zero
#define hw_trezor_messages_management_SESignMessage_init_zero SESignMessage_init_zero
#define hw_trezor_messages_management_SEMessageSignature_init_zero SEMessageSignature_init_zero
#define hw_trezor_messages_management_SEInitialize_init_zero SEInitialize_init_zero
#define hw_trezor_messages_management_SEInitializeDone_init_zero SEInitializeDone_init_zero
#define hw_trezor_messages_management_SEBackToRomBoot_init_zero SEBackToRomBoot_init_zero
#define hw_trezor_messages_management_SEWipeUserStorage_init_zero SEWipeUserStorage_init_zero
#define hw_trezor_messages_management_ResourceUpload_init_zero ResourceUpload_init_zero
#define hw_trezor_messages_management_ZoomRequest_init_zero ZoomRequest_init_zero
#define hw_trezor_messages_management_ResourceRequest_init_zero ResourceRequest_init_zero
#define hw_trezor_messages_management_ResourceAck_init_zero ResourceAck_init_zero
#define hw_trezor_messages_management_ResourceUpdate_init_zero ResourceUpdate_init_zero
#define hw_trezor_messages_management_ListResDir_init_zero ListResDir_init_zero
#define hw_trezor_messages_management_FileInfoList_init_zero FileInfoList_init_zero
#define hw_trezor_messages_management_FileInfo_init_zero FileInfo_init_zero
#define hw_trezor_messages_management_UnlockPath_init_zero UnlockPath_init_zero
#define hw_trezor_messages_management_UnlockedPathRequest_init_zero UnlockedPathRequest_init_zero

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
