/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "messages-common.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Success, Success, 2)


PB_BIND(Failure, Failure, 2)


PB_BIND(ButtonRequest, ButtonRequest, AUTO)


PB_BIND(ButtonAck, ButtonAck, AUTO)


PB_BIND(PinMatrixRequest, PinMatrixRequest, AUTO)


PB_BIND(PinMatrixAck, PinMatrixAck, AUTO)


PB_BIND(PassphraseRequest, PassphraseRequest, AUTO)


PB_BIND(PassphraseAck, PassphraseAck, AUTO)


PB_BIND(Deprecated_PassphraseStateRequest, Deprecated_PassphraseStateRequest, AUTO)


PB_BIND(Deprecated_PassphraseStateAck, Deprecated_PassphraseStateAck, AUTO)


PB_BIND(HDNodeType, HDNodeType, AUTO)






