/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "messages-fs.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(FsInfo, FsInfo, 2)


PB_BIND(FsChunk, FsChunk, 4)


PB_BIND(FsRead, FsRead, 2)


PB_BIND(FsWrite, FsWrite, 4)


PB_BIND(FsRemove, FsRemove, 2)


PB_BIND(FsMkdir, FsMkdir, 2)


PB_BIND(FsStat, FsStat, 2)


PB_BIND(FsFsStat, FsFsStat, AUTO)


PB_BIND(FsFsInfo, FsFsInfo, AUTO)


PB_BIND(FsFile, FsFile, 4)


PB_BIND(FsFileRead, FsFileRead, 4)


PB_BIND(FsFileWrite, FsFileWrite, 4)


PB_BIND(FsChecksums, FsChecksums, AUTO)




