#define VERSION_MAJOR 1
#define VERSION_MINOR 2
#define VERSION_PATCH 29
#define VERSION_BUILD 0

#define FIX_VERSION_MAJOR 1
#define FIX_VERSION_MINOR 2
#define FIX_VERSION_PATCH 29
#define FIX_VERSION_BUILD 0

#define HYPERMATE_VERSION_MAJOR 1
#define HYPERMATE_VERSION_MINOR 2
#define HYPERMATE_VERSION_PATCH 29
#define HYPERMATE_VERSION_BUILD 0

#define HYPERMATE_VERSION "1.2.29"
